/* !!!IMPORTANT!!!: This file is a data table file. All code is generated by the table export BAT tool. Do not modify the .cs file directly. Please modify the original Excel file first and then regenerate the code using the tool.*/
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Z_ByteSerialize;
using Z_DesignStyle;
using Z_UnitSystem.Form;
using Z_Text.Form;
using Z_DataSystem.Form;
using Z_Map.Form;
using Z_Map;
using Z_Ui.Form;
using Z_Code.Form;

namespace Form
{

    public static partial class EffectForm
    {
public static readonly int autoUidCnt=100;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Register()
        {



            Z_Json.extra[typeof(Data)]=((obj)=>{
            if(obj is Data data)
                return GetJoByData(data);
            return null;
            },(jo)=>{
            return GetDataByJo(jo);
            });
        }
        
        private static bool inited;

        public static Z_Chain.Chain uidChain ;

        public static Action<Data> addAction;
        public static Action<Data> removeAction;
        public static Action childInitAction;
        public static Action<Data> childRemoveAction;
        public static Action<Data> childAddAction;
        
        public static Action<Data> beforeGetAction;

        public static Action<Data,int,int> changeUidAction;
                
        public static Action<Data,string,string> changeNameAction;
                
        public static Action<Data,int,int> changeLabidAction;
                
        public static Action<Data,List<List<EffectClipForm.Data>>,List<List<EffectClipForm.Data>>> changeClipsAction;
                
        public static Action<Data,bool,bool> changeGroundAction;
                


        public partial class Data
        {

                    private int  _uid;
                    /// <summary>
                    ///
                    ///</summary>
                    public int  uid{
                                get{return _uid;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeUid(this,_uid,value); 
                    }
        
                _uid = value;
                }
                 
                     }
                    
                    private string  _name;
                    /// <summary>
                    ///名称
                    ///</summary>
                    public string  name{
                                get{return _name;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeName(this,_name,value); 
                    }
        
                _name = value;
                }
                 
                     }
                    
                    private int  _labId;
                    /// <summary>
                    ///标签
                    ///</summary>
                    public int  labId{
                                get{return _labId;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLabid(this,_labId,value); 
                    }
        
                _labId = value;
                }
                 
                     }
                    
                    private List<List<EffectClipForm.Data>>  _clips;
                    /// <summary>
                    ///
                    ///</summary>
                    public List<List<EffectClipForm.Data>>  clips{
                                get{return _clips;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeClips(this,_clips,value); 
                    }
        
                _clips = value;
                }
                 
                     }
                    
                    private bool  _ground;
                    /// <summary>
                    ///地面特效
                    ///</summary>
                    public bool  ground{
                                get{return _ground;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeGround(this,_ground,value); 
                    }
        
                _ground = value;
                }
                 
                     }
                    
            public Data(int uid,string name,int labId,List<List<EffectClipForm.Data>> clips,bool ground)
            {

             this.uid = uid;
             this.name = name;
             this.labId = labId;
             this.clips = clips;
             this.ground = ground;

            }
            public void Reset(Data data)
            {

             this.uid = data.uid;
             this.name = data.name;
             this.labId = data.labId;
             this.clips = data.clips;
             this.ground = data.ground;
            }

                public Data Copy(bool sameId = true)
                {
        return new Data(sameId? uid:uidChain.GetId(),name,labId,clips==null?new List<List<EffectClipForm.Data>>():new List<List<EffectClipForm.Data>>(clips),ground);
                }
            
            public virtual  void BeforeGet()
            {
                
                EffectForm.beforeGetAction?.Invoke(this);
            }
        }

                   private static Data _defaultData=new Data(0,"",0,null,false);
                   public static Data defaultData=>_defaultData.Copy();


            static HashSet<Data> _DatasHashSet;
            static Dictionary<int, Data> _DataByUid;
            public static Dictionary<int, Data> DataByUid
            {
                get
                {
                    Init();
                    return _DataByUid;
                }
            }
    
            static Dictionary<int, List<Data>> _DatasByLabid;
            public static Dictionary<int, List<Data>> DatasByLabid
            {
                get
                {
                    Init();
                    return _DatasByLabid;
                }
            }
    
            static Dictionary<string, Data> _DataByName;
            public static Dictionary<string, Data> DataByName
            {
                get
                {
                    Init();
                    return _DataByName;
                }
            }
    

        static public void Init()
        {

            InitInternal();
        }
        public static void InitInternal()
        {
            if(inited)
                return;
            inited=true;  
uidChain=new Z_Chain.Chain (autoUidCnt);

                _DataByUid = new Dictionary<int, Data>() {

                };
                _DatasHashSet=new HashSet<Data>();
                
                    _DataByName = new Dictionary<string, Data>() {
    
                    
                    };
                    foreach(var v in _DataByUid.Values)
                    {
                        _DatasHashSet.Add(v);
                    }
    
                    _DatasByLabid = new Dictionary<int, List<Data>>() {
    
                };


            childInitAction?.Invoke();
            

foreach(var k in _DataByUid.Keys){ uidChain.PopId(k); }
             
        }


        public static List<Data> GetDatasByJa(JArray ja)
        {
            Init();
            List<Data> lst=new List<Data>();
            foreach(JObject jo in ja)
            {
                if(jo.Get<int>("uid")==0)
                    continue;
                lst.Add(GetDataByJo(jo));
            }
            return lst;
        }

        public static JArray GetJaByDatas()
        {
            Init();
            JArray ja=new JArray();
            foreach(Data data in _DataByUid.Values)
            {
                if(data.uid==0)
                    continue;
                ja.Add(GetJoByData(data));
            }
            return ja;
        }

        public static Data GetDataByJo(JObject jo)
        {
            Init();

            Data data=new Data(

                jo.SelectToken("uid")==null?defaultData.uid:jo.Get<int>("uid"),

                jo.SelectToken("name")==null?defaultData.name:jo.Get<string>("name"),

                jo.SelectToken("labId")==null?defaultData.labId:jo.Get<int>("labId"),

                jo.SelectToken("clips")==null?defaultData.clips:jo.Get<List<List<EffectClipForm.Data>>>("clips"),

                jo.SelectToken("ground")==null?defaultData.ground:jo.Get<bool>("ground")
                    );

            return data;
        }

        public static JObject GetJoByData(Data data)
        {
            Init();
            data.BeforeGet();

            JObject jo=new JObject();

            jo.Set<int>("uid",data.uid);

            jo.Set<string>("name",data.name);

            jo.Set<int>("labId",data.labId);

            jo.Set<List<List<EffectClipForm.Data>>>("clips",data.clips);

            jo.Set<bool>("ground",data.ground);

            return jo;
        }


        public static int AddData(Data data)
        {
            Init();
            if(DataByUid.ContainsKey(data.uid))
                return data.uid;
            if(data.uid==-1)
            { 
                int uid=uidChain.GetId();
                if(uid==-1)
                    return -1;
                data.uid=uid;  
            }
            uidChain.PopId(data.uid);

        DataByUid[data.uid]=data;
        _DatasHashSet.Add(data);
    
                    DataByName[data.name]=data;
    
                    if(!DatasByLabid.ContainsKey(data.labId))
                        DatasByLabid[data.labId]=new List<Data>();
                    DatasByLabid[data.labId].Add(data);
    

            childAddAction?.Invoke(data);
            addAction?.Invoke(data);
            return data.uid;
        }
        public static void RemoveData(int uid)
        {            
            Init();
            if(!DataByUid.ContainsKey(uid))
                return;
               
            var data=DataByUid[uid];

                    _DatasHashSet.Remove(DataByUid[data.uid]);
                    DataByUid.Remove(data.uid);
                    
    
                    DataByName.Remove(data.name);
    
                    if(DatasByLabid.ContainsKey(data.labId))
                    {
                        DatasByLabid[data.labId].Remove(data);
                        if(DatasByLabid[data.labId].Count==0)
                            DatasByLabid.Remove(data.labId);
                    }
                    
    

            uidChain.PushId(data.uid);
            childRemoveAction?.Invoke(data);
            removeAction?.Invoke(data);
        }
        public static void Clear()
        {
            Init();
            var keys = new List<int>(DataByUid.Keys);
            foreach(var key in keys)
            {
                    RemoveData(key);
            }

        }
        
        public static void ClearAuto()
        {
            Init();
            var keys = new List<int>(DataByUid.Keys);
            foreach(var key in keys)
            {
                if(key < uidChain.cnt)
                    {
                        RemoveData(key);
                    }
            }
        }

         private static void RemoveChildren(Data data)
        {
            Init();
            if(data is Data)
               RemoveData(data.uid);      
        }
         private static void AddChildren(Data superData)
        {
            Init();
            if(superData is Data data)
               AddData(data);      
        }
        




            public static void ChangeUid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeUidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeName(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DataByName.Remove(oldV);
                    DataByName[newV]=data;
 
                changeNameAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLabid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                    DatasByLabid[oldV].Remove(data);
                    if(DatasByLabid[oldV].Count==0)
                        DatasByLabid.Remove(oldV);
                    if(!DatasByLabid.ContainsKey(newV))
                        DatasByLabid[newV]=new List<Data>();
                    DatasByLabid[newV].Add(data);
 
                changeLabidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeClips(Data superData,List<List<EffectClipForm.Data>> oldV,List<List<EffectClipForm.Data>> newV)
            {
                if(superData is Data data)
                {

                changeClipsAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeGround(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeGroundAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
    }
}
        