/* !!!IMPORTANT!!!: This file is a data table file. All code is generated by the table export BAT tool. Do not modify the .cs file directly. Please modify the original Excel file first and then regenerate the code using the tool.*/
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Z_ByteSerialize;
using Z_DesignStyle;
using Z_UnitSystem.Form;
using Z_Text.Form;
using Z_DataSystem.Form;
using Z_Map.Form;
using Z_Map;
using Z_Ui.Form;
using Z_Code.Form;

namespace Form
{

    public static partial class MapTypeForm
    {
public static readonly int autoIdCnt=100;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Register()
        {



            Z_Json.extra[typeof(Data)]=((obj)=>{
            if(obj is Data data)
                return GetJoByData(data);
            return null;
            },(jo)=>{
            return GetDataByJo(jo);
            });
        }
        
        private static bool inited;

        public static Z_Chain.Chain idChain ;

        public static Action<Data> addAction;
        public static Action<Data> removeAction;
        public static Action childInitAction;
        public static Action<Data> childRemoveAction;
        public static Action<Data> childAddAction;
        
        public static Action<Data> beforeGetAction;



        public partial class Data
        {

                    private int  _id;
                    /// <summary>
                    ///
                    ///</summary>
                    public int  id{
                                get{return _id;}
private set{
        
                _id = value;
                }
                 
                     }
                    
                    private string  _NameKey;
                    /// <summary>
                    ///名称索引
                    ///</summary>
                    public string  NameKey{
                                get{return _NameKey;}
private set{
        
                _NameKey = value;
                }
                 
                     }
                    
                    private int  _icon;
                    /// <summary>
                    ///图标
                    ///</summary>
                    public int  icon{
                                get{return _icon;}
private set{
        
                _icon = value;
                }
                 
                     }
                    
                    private bool  _needLayer;
                    /// <summary>
                    ///是否需要层级设置
                    ///</summary>
                    public bool  needLayer{
                                get{return _needLayer;}
private set{
        
                _needLayer = value;
                }
                 
                     }
                    
            public Data(int id,string NameKey,int icon,bool needLayer)
            {

             this.id = id;
             this.NameKey = NameKey;
             this.icon = icon;
             this.needLayer = needLayer;

            }
            public void Reset(Data data)
            {

             this.id = data.id;
             this.NameKey = data.NameKey;
             this.icon = data.icon;
             this.needLayer = data.needLayer;
            }

                public Data Copy(bool sameId = true)
                {
        return new Data(sameId? id:idChain.GetId(),NameKey,icon,needLayer);
                }
            
            public virtual  void BeforeGet()
            {
                
                MapTypeForm.beforeGetAction?.Invoke(this);
            }
        }

                   private static Data _defaultData=new Data(0,"",0,false);
                   public static Data defaultData=>_defaultData.Copy();


            static HashSet<Data> _DatasHashSet;
            static Dictionary<int, Data> _DataById;
            public static Dictionary<int, Data> DataById
            {
                get
                {
                    Init();
                    return _DataById;
                }
            }
    

        static public void Init()
        {

            InitInternal();
        }
        public static void InitInternal()
        {
            if(inited)
                return;
            inited=true;  
idChain=new Z_Chain.Chain (autoIdCnt);

                _DataById = new Dictionary<int, Data>() {

                {1,new Data(1,"terrain",0,false)},

                {2,new Data(2,"texture",0,true)},

                {3,new Data(3,"transitionMask",0,true)},

                {4,new Data(4,"object",0,false)},

                {5,new Data(5,"item",0,false)},

                {6,new Data(6,"character",0,false)},

                {100,new Data(100,"erase",0,false)},

                };
                _DatasHashSet=new HashSet<Data>();
                

            childInitAction?.Invoke();
            

foreach(var k in _DataById.Keys){ idChain.PopId(k); }
             
        }


        public static List<Data> GetDatasByJa(JArray ja)
        {
            Init();
            List<Data> lst=new List<Data>();
            foreach(JObject jo in ja)
            {
                if(jo.Get<int>("id")==0)
                    continue;
                lst.Add(GetDataByJo(jo));
            }
            return lst;
        }

        public static JArray GetJaByDatas()
        {
            Init();
            JArray ja=new JArray();
            foreach(Data data in _DataById.Values)
            {
                if(data.id==0)
                    continue;
                ja.Add(GetJoByData(data));
            }
            return ja;
        }

        public static Data GetDataByJo(JObject jo)
        {
            Init();

            Data data=new Data(

                jo.SelectToken("id")==null?defaultData.id:jo.Get<int>("id"),

                    _defaultData.NameKey,

                    _defaultData.icon,

                    _defaultData.needLayer
                    );

            return data;
        }

        public static JObject GetJoByData(Data data)
        {
            Init();
            data.BeforeGet();

            JObject jo=new JObject();

            jo.Set<int>("id",data.id);

            return jo;
        }




    }
}
        