/* !!!IMPORTANT!!!: This file is a data table file. All code is generated by the table export BAT tool. Do not modify the .cs file directly. Please modify the original Excel file first and then regenerate the code using the tool.*/
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Z_ByteSerialize;
using Z_DesignStyle;
using Z_UnitSystem.Form;
using Z_Text.Form;
using Z_DataSystem.Form;
using Z_Map.Form;
using Z_Map;
using Z_Ui.Form;
using Z_Code.Form;

namespace Form
{

    public static partial class ProgressForm
    {
public static readonly int autoUidCnt=100;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Register()
        {



            Z_Json.extra[typeof(Data)]=((obj)=>{
            if(obj is Data data)
                return GetJoByData(data);
            return null;
            },(jo)=>{
            return GetDataByJo(jo);
            });
        }
        
        private static bool inited;

        public static Z_Chain.Chain uidChain ;

        public static Action<Data> addAction;
        public static Action<Data> removeAction;
        public static Action childInitAction;
        public static Action<Data> childRemoveAction;
        public static Action<Data> childAddAction;
        
        public static Action<Data> beforeGetAction;

        public static Action<Data,int,int> changeUidAction;
                
        public static Action<Data,float,float> changeSecondsAction;
                
        public static Action<Data,int,int> changeSceneidAction;
                
        public static Action<Data,Vector3,Vector3> changePosAction;
                
        public static Action<Data,int,int> changeCharacteruidAction;
                
        public static Action<Data,List<int>,List<int>> changeBagAction;
                
        public static Action<Data,List<int>,List<int>> changeTeamAction;
                
        public static Action<Data,List<int>,List<int>> changeTeamactiveAction;
                
        public static Action<Data,Dictionary<string,string>,Dictionary<string,string>> changeUistyleimagenameAction;
                
        public static Action<Data,CameraMode,CameraMode> changeCameramodeAction;
                
        public static Action<Data,ClipForm.Data,ClipForm.Data> changeDialogcacheAction;
                
        public static Action<Data,int,int> changeBlockprogramuidAction;
                
        public static Action<Data,EditorStyle,EditorStyle> changeEditorstyleAction;
                
        public static Action<Data,bool,bool> changeEnableequipAction;
                
        public static Action<Data,bool,bool> changeEnableskillAction;
                
        public static Action<Data,bool,bool> changeEnablefreechangeactiveteamerAction;
                
        public static Action<Data,bool,bool> changeEnablefreechangeskillAction;
                
        public static Action<Data,bool,bool> changeEnableminimapAction;
                
        public static Action<Data,bool,bool> changeEnablelargemapAction;
                
        public static Action<Data,bool,bool> changeEnablemissionAction;
                
        public static Action<Data,int,int> changeLargemapAction;
                
        public static Action<Data,int,int> changeCurmissionidAction;
                
        public static Action<Data,(int,Vector3),(int,Vector3)> changeTargetsceneAction;
                
        public static Action<Data,bool,bool> changeBanscenechangeAction;
                
        public static Action<Data,EventState,EventState> changeEventstateAction;
                


        public partial class Data
        {

                    private int  _uid;
                    /// <summary>
                    ///
                    ///</summary>
                    public int  uid{
                                get{return _uid;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeUid(this,_uid,value); 
                    }
        
                _uid = value;
                }
                 
                     }
                    
                    private float  _seconds;
                    /// <summary>
                    ///时长
                    ///</summary>
                    public float  seconds{
                                get{return _seconds;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeSeconds(this,_seconds,value); 
                    }
        
                _seconds = value;
                }
                 
                     }
                    
                    private int  _sceneId;
                    /// <summary>
                    ///玩家所处sceneId
                    ///</summary>
                    public int  sceneId{
                                get{return _sceneId;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeSceneid(this,_sceneId,value); 
                    }
        
                _sceneId = value;
                }
                 
                     }
                    
                    private Vector3  _pos;
                    /// <summary>
                    ///玩家位置
                    ///</summary>
                    public Vector3  pos{
                                get{return _pos;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangePos(this,_pos,value); 
                    }
        
                _pos = value;
                }
                 
                     }
                    
                    private int  _characterUid;
                    /// <summary>
                    ///玩家角色Uid
                    ///</summary>
                    public int  characterUid{
                                get{return _characterUid;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeCharacteruid(this,_characterUid,value); 
                    }
        
                _characterUid = value;
                }
                 
                     }
                    
                    private List<int>  _bag;
                    /// <summary>
                    ///背包（道具uid）
                    ///</summary>
                    public List<int>  bag{
                                get{return _bag;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeBag(this,_bag,value); 
                    }
        
                _bag = value;
                }
                 
                     }
                    
                    private List<int>  _team;
                    /// <summary>
                    ///队伍（人物uid）
                    ///</summary>
                    public List<int>  team{
                                get{return _team;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeTeam(this,_team,value); 
                    }
        
                _team = value;
                }
                 
                     }
                    
                    private List<int>  _teamActive;
                    /// <summary>
                    ///出战队伍（人物uid）
                    ///</summary>
                    public List<int>  teamActive{
                                get{return _teamActive;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeTeamactive(this,_teamActive,value); 
                    }
        
                _teamActive = value;
                }
                 
                     }
                    
                    private Dictionary<string,string>  _uiStyleImageName;
                    /// <summary>
                    ///ui样式图片名称
                    ///</summary>
                    public Dictionary<string,string>  uiStyleImageName{
                                get{return _uiStyleImageName;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeUistyleimagename(this,_uiStyleImageName,value); 
                    }
        
                _uiStyleImageName = value;
                }
                 
                     }
                    
                    private CameraMode  _cameraMode;
                    /// <summary>
                    ///相机视角
                    ///</summary>
                    public CameraMode  cameraMode{
                                get{return _cameraMode;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeCameramode(this,_cameraMode,value); 
                    }
        
                _cameraMode = value;
                }
                 
                     }
                    
                    private ClipForm.Data  _dialogCache;
                    /// <summary>
                    ///对话缓存
                    ///</summary>
                    public ClipForm.Data  dialogCache{
                                get{return _dialogCache;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeDialogcache(this,_dialogCache,value); 
                    }
        
                _dialogCache = value;
                }
                 
                     }
                    
                    private int  _blockProgramUid;
                    /// <summary>
                    ///阻塞的程序uid
                    ///</summary>
                    public int  blockProgramUid{
                                get{return _blockProgramUid;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeBlockprogramuid(this,_blockProgramUid,value); 
                    }
        
                _blockProgramUid = value;
                }
                 
                     }
                    
                    private EditorStyle  _editorStyle;
                    /// <summary>
                    ///编辑模式
                    ///</summary>
                    public EditorStyle  editorStyle{
                                get{return _editorStyle;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEditorstyle(this,_editorStyle,value); 
                    }
        
                _editorStyle = value;
                }
                 
                     }
                    
                    private bool  _enableEquip;
                    /// <summary>
                    ///启用装备
                    ///</summary>
                    public bool  enableEquip{
                                get{return _enableEquip;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnableequip(this,_enableEquip,value); 
                    }
        
                _enableEquip = value;
                }
                 
                     }
                    
                    private bool  _enableSkill;
                    /// <summary>
                    ///启用技能
                    ///</summary>
                    public bool  enableSkill{
                                get{return _enableSkill;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnableskill(this,_enableSkill,value); 
                    }
        
                _enableSkill = value;
                }
                 
                     }
                    
                    private bool  _enableFreeChangeActiveTeamer;
                    /// <summary>
                    ///启用随时出战
                    ///</summary>
                    public bool  enableFreeChangeActiveTeamer{
                                get{return _enableFreeChangeActiveTeamer;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnablefreechangeactiveteamer(this,_enableFreeChangeActiveTeamer,value); 
                    }
        
                _enableFreeChangeActiveTeamer = value;
                }
                 
                     }
                    
                    private bool  _enableFreeChangeSkill;
                    /// <summary>
                    ///启用随时改技能
                    ///</summary>
                    public bool  enableFreeChangeSkill{
                                get{return _enableFreeChangeSkill;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnablefreechangeskill(this,_enableFreeChangeSkill,value); 
                    }
        
                _enableFreeChangeSkill = value;
                }
                 
                     }
                    
                    private bool  _enableMinimap;
                    /// <summary>
                    ///启用小地图
                    ///</summary>
                    public bool  enableMinimap{
                                get{return _enableMinimap;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnableminimap(this,_enableMinimap,value); 
                    }
        
                _enableMinimap = value;
                }
                 
                     }
                    
                    private bool  _enableLargeMap;
                    /// <summary>
                    ///启用大地图
                    ///</summary>
                    public bool  enableLargeMap{
                                get{return _enableLargeMap;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnablelargemap(this,_enableLargeMap,value); 
                    }
        
                _enableLargeMap = value;
                }
                 
                     }
                    
                    private bool  _enableMission;
                    /// <summary>
                    ///启用任务
                    ///</summary>
                    public bool  enableMission{
                                get{return _enableMission;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEnablemission(this,_enableMission,value); 
                    }
        
                _enableMission = value;
                }
                 
                     }
                    
                    private int  _largeMap;
                    /// <summary>
                    ///大地图
                    ///</summary>
                    public int  largeMap{
                                get{return _largeMap;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLargemap(this,_largeMap,value); 
                    }
        
                _largeMap = value;
                }
                 
                     }
                    
                    private int  _curMissionId;
                    /// <summary>
                    ///当前任务
                    ///</summary>
                    public int  curMissionId{
                                get{return _curMissionId;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeCurmissionid(this,_curMissionId,value); 
                    }
        
                _curMissionId = value;
                }
                 
                     }
                    
                    private (int,Vector3)  _targetScene;
                    /// <summary>
                    ///目标scene
                    ///</summary>
                    public (int,Vector3)  targetScene{
                                get{return _targetScene;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeTargetscene(this,_targetScene,value); 
                    }
        
                _targetScene = value;
                }
                 
                     }
                    
                    private bool  _banSceneChange;
                    /// <summary>
                    ///禁止场景传送
                    ///</summary>
                    public bool  banSceneChange{
                                get{return _banSceneChange;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeBanscenechange(this,_banSceneChange,value); 
                    }
        
                _banSceneChange = value;
                }
                 
                     }
                    
                    private EventState  _eventState;
                    /// <summary>
                    ///事件状态
                    ///</summary>
                    public EventState  eventState{
                                get{return _eventState;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeEventstate(this,_eventState,value); 
                    }
        
                _eventState = value;
                }
                 
                     }
                    
            public Data(int uid,float seconds,int sceneId,Vector3 pos,int characterUid,List<int> bag,List<int> team,List<int> teamActive,Dictionary<string,string> uiStyleImageName,CameraMode cameraMode,ClipForm.Data dialogCache,int blockProgramUid,EditorStyle editorStyle,bool enableEquip,bool enableSkill,bool enableFreeChangeActiveTeamer,bool enableFreeChangeSkill,bool enableMinimap,bool enableLargeMap,bool enableMission,int largeMap,int curMissionId,(int,Vector3) targetScene,bool banSceneChange,EventState eventState)
            {

             this.uid = uid;
             this.seconds = seconds;
             this.sceneId = sceneId;
             this.pos = pos;
             this.characterUid = characterUid;
             this.bag = bag;
             this.team = team;
             this.teamActive = teamActive;
             this.uiStyleImageName = uiStyleImageName;
             this.cameraMode = cameraMode;
             this.dialogCache = dialogCache;
             this.blockProgramUid = blockProgramUid;
             this.editorStyle = editorStyle;
             this.enableEquip = enableEquip;
             this.enableSkill = enableSkill;
             this.enableFreeChangeActiveTeamer = enableFreeChangeActiveTeamer;
             this.enableFreeChangeSkill = enableFreeChangeSkill;
             this.enableMinimap = enableMinimap;
             this.enableLargeMap = enableLargeMap;
             this.enableMission = enableMission;
             this.largeMap = largeMap;
             this.curMissionId = curMissionId;
             this.targetScene = targetScene;
             this.banSceneChange = banSceneChange;
             this.eventState = eventState;

            }
            public void Reset(Data data)
            {

             this.uid = data.uid;
             this.seconds = data.seconds;
             this.sceneId = data.sceneId;
             this.pos = data.pos;
             this.characterUid = data.characterUid;
             this.bag = data.bag;
             this.team = data.team;
             this.teamActive = data.teamActive;
             this.uiStyleImageName = data.uiStyleImageName;
             this.cameraMode = data.cameraMode;
             this.dialogCache = data.dialogCache;
             this.blockProgramUid = data.blockProgramUid;
             this.editorStyle = data.editorStyle;
             this.enableEquip = data.enableEquip;
             this.enableSkill = data.enableSkill;
             this.enableFreeChangeActiveTeamer = data.enableFreeChangeActiveTeamer;
             this.enableFreeChangeSkill = data.enableFreeChangeSkill;
             this.enableMinimap = data.enableMinimap;
             this.enableLargeMap = data.enableLargeMap;
             this.enableMission = data.enableMission;
             this.largeMap = data.largeMap;
             this.curMissionId = data.curMissionId;
             this.targetScene = data.targetScene;
             this.banSceneChange = data.banSceneChange;
             this.eventState = data.eventState;
            }

                public Data Copy(bool sameId = true)
                {
        return new Data(sameId? uid:uidChain.GetId(),seconds,sceneId,pos,characterUid,bag==null?new List<int>():new List<int>(bag),team==null?new List<int>():new List<int>(team),teamActive==null?new List<int>():new List<int>(teamActive),uiStyleImageName==null?new Dictionary<string,string>():new Dictionary<string,string>(uiStyleImageName),cameraMode,dialogCache,blockProgramUid,editorStyle,enableEquip,enableSkill,enableFreeChangeActiveTeamer,enableFreeChangeSkill,enableMinimap,enableLargeMap,enableMission,largeMap,curMissionId,targetScene,banSceneChange,eventState);
                }
            
            public virtual  void BeforeGet()
            {
                
                ProgressForm.beforeGetAction?.Invoke(this);
            }
        }

                   private static Data _defaultData=new Data(0,0f,0,Vector3.zero,0,null,null,null,new Dictionary<string,string>(){},CameraMode.Overhead,ClipForm.defaultData,0,EditorStyle.Avg,false,false,false,false,false,false,false,0,0,(0,Vector3.zero),false,default);
                   public static Data defaultData=>_defaultData.Copy();


            static HashSet<Data> _DatasHashSet;
            static Dictionary<int, Data> _DataByUid;
            public static Dictionary<int, Data> DataByUid
            {
                get
                {
                    Init();
                    return _DataByUid;
                }
            }
    

        static public void Init()
        {

            InitInternal();
        }
        public static void InitInternal()
        {
            if(inited)
                return;
            inited=true;  
uidChain=new Z_Chain.Chain (autoUidCnt);

                _DataByUid = new Dictionary<int, Data>() {

                };
                _DatasHashSet=new HashSet<Data>();
                

            childInitAction?.Invoke();
            

foreach(var k in _DataByUid.Keys){ uidChain.PopId(k); }
             
        }


        public static List<Data> GetDatasByJa(JArray ja)
        {
            Init();
            List<Data> lst=new List<Data>();
            foreach(JObject jo in ja)
            {
                if(jo.Get<int>("uid")==0)
                    continue;
                lst.Add(GetDataByJo(jo));
            }
            return lst;
        }

        public static JArray GetJaByDatas()
        {
            Init();
            JArray ja=new JArray();
            foreach(Data data in _DataByUid.Values)
            {
                if(data.uid==0)
                    continue;
                ja.Add(GetJoByData(data));
            }
            return ja;
        }

        public static Data GetDataByJo(JObject jo)
        {
            Init();

            Data data=new Data(

                jo.SelectToken("uid")==null?defaultData.uid:jo.Get<int>("uid"),

                jo.SelectToken("seconds")==null?defaultData.seconds:jo.Get<float>("seconds"),

                jo.SelectToken("sceneId")==null?defaultData.sceneId:jo.Get<int>("sceneId"),

                jo.SelectToken("pos")==null?defaultData.pos:jo.Get<Vector3>("pos"),

                jo.SelectToken("characterUid")==null?defaultData.characterUid:jo.Get<int>("characterUid"),

                jo.SelectToken("bag")==null?defaultData.bag:jo.Get<List<int>>("bag"),

                jo.SelectToken("team")==null?defaultData.team:jo.Get<List<int>>("team"),

                jo.SelectToken("teamActive")==null?defaultData.teamActive:jo.Get<List<int>>("teamActive"),

                jo.SelectToken("uiStyleImageName")==null?defaultData.uiStyleImageName:jo.Get<Dictionary<string,string>>("uiStyleImageName"),

                jo.SelectToken("cameraMode")==null?defaultData.cameraMode:jo.Get<CameraMode>("cameraMode"),

                jo.SelectToken("dialogCache")==null?defaultData.dialogCache:jo.Get<ClipForm.Data>("dialogCache"),

                jo.SelectToken("blockProgramUid")==null?defaultData.blockProgramUid:jo.Get<int>("blockProgramUid"),

                jo.SelectToken("editorStyle")==null?defaultData.editorStyle:jo.Get<EditorStyle>("editorStyle"),

                jo.SelectToken("enableEquip")==null?defaultData.enableEquip:jo.Get<bool>("enableEquip"),

                jo.SelectToken("enableSkill")==null?defaultData.enableSkill:jo.Get<bool>("enableSkill"),

                jo.SelectToken("enableFreeChangeActiveTeamer")==null?defaultData.enableFreeChangeActiveTeamer:jo.Get<bool>("enableFreeChangeActiveTeamer"),

                jo.SelectToken("enableFreeChangeSkill")==null?defaultData.enableFreeChangeSkill:jo.Get<bool>("enableFreeChangeSkill"),

                jo.SelectToken("enableMinimap")==null?defaultData.enableMinimap:jo.Get<bool>("enableMinimap"),

                jo.SelectToken("enableLargeMap")==null?defaultData.enableLargeMap:jo.Get<bool>("enableLargeMap"),

                jo.SelectToken("enableMission")==null?defaultData.enableMission:jo.Get<bool>("enableMission"),

                jo.SelectToken("largeMap")==null?defaultData.largeMap:jo.Get<int>("largeMap"),

                jo.SelectToken("curMissionId")==null?defaultData.curMissionId:jo.Get<int>("curMissionId"),

                jo.SelectToken("targetScene")==null?defaultData.targetScene:jo.Get<(int,Vector3)>("targetScene"),

                jo.SelectToken("banSceneChange")==null?defaultData.banSceneChange:jo.Get<bool>("banSceneChange"),

                jo.SelectToken("eventState")==null?defaultData.eventState:jo.Get<EventState>("eventState")
                    );

            return data;
        }

        public static JObject GetJoByData(Data data)
        {
            Init();
            data.BeforeGet();

            JObject jo=new JObject();

            jo.Set<int>("uid",data.uid);

            jo.Set<float>("seconds",data.seconds);

            jo.Set<int>("sceneId",data.sceneId);

            jo.Set<Vector3>("pos",data.pos);

            jo.Set<int>("characterUid",data.characterUid);

            jo.Set<List<int>>("bag",data.bag);

            jo.Set<List<int>>("team",data.team);

            jo.Set<List<int>>("teamActive",data.teamActive);

            jo.Set<Dictionary<string,string>>("uiStyleImageName",data.uiStyleImageName);

            jo.Set<CameraMode>("cameraMode",data.cameraMode);

            jo.Set<ClipForm.Data>("dialogCache",data.dialogCache);

            jo.Set<int>("blockProgramUid",data.blockProgramUid);

            jo.Set<EditorStyle>("editorStyle",data.editorStyle);

            jo.Set<bool>("enableEquip",data.enableEquip);

            jo.Set<bool>("enableSkill",data.enableSkill);

            jo.Set<bool>("enableFreeChangeActiveTeamer",data.enableFreeChangeActiveTeamer);

            jo.Set<bool>("enableFreeChangeSkill",data.enableFreeChangeSkill);

            jo.Set<bool>("enableMinimap",data.enableMinimap);

            jo.Set<bool>("enableLargeMap",data.enableLargeMap);

            jo.Set<bool>("enableMission",data.enableMission);

            jo.Set<int>("largeMap",data.largeMap);

            jo.Set<int>("curMissionId",data.curMissionId);

            jo.Set<(int,Vector3)>("targetScene",data.targetScene);

            jo.Set<bool>("banSceneChange",data.banSceneChange);

            jo.Set<EventState>("eventState",data.eventState);

            return jo;
        }


        public static int AddData(Data data)
        {
            Init();
            if(DataByUid.ContainsKey(data.uid))
                return data.uid;
            if(data.uid==-1)
            { 
                int uid=uidChain.GetId();
                if(uid==-1)
                    return -1;
                data.uid=uid;  
            }
            uidChain.PopId(data.uid);

        DataByUid[data.uid]=data;
        _DatasHashSet.Add(data);
    

            childAddAction?.Invoke(data);
            addAction?.Invoke(data);
            return data.uid;
        }
        public static void RemoveData(int uid)
        {            
            Init();
            if(!DataByUid.ContainsKey(uid))
                return;
               
            var data=DataByUid[uid];

                    _DatasHashSet.Remove(DataByUid[data.uid]);
                    DataByUid.Remove(data.uid);
                    
    

            uidChain.PushId(data.uid);
            childRemoveAction?.Invoke(data);
            removeAction?.Invoke(data);
        }
        public static void Clear()
        {
            Init();
            var keys = new List<int>(DataByUid.Keys);
            foreach(var key in keys)
            {
                    RemoveData(key);
            }

        }
        
        public static void ClearAuto()
        {
            Init();
            var keys = new List<int>(DataByUid.Keys);
            foreach(var key in keys)
            {
                if(key < uidChain.cnt)
                    {
                        RemoveData(key);
                    }
            }
        }

         private static void RemoveChildren(Data data)
        {
            Init();
            if(data is Data)
               RemoveData(data.uid);      
        }
         private static void AddChildren(Data superData)
        {
            Init();
            if(superData is Data data)
               AddData(data);      
        }
        




            public static void ChangeUid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeUidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeSeconds(Data superData,float oldV,float newV)
            {
                if(superData is Data data)
                {

                changeSecondsAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeSceneid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeSceneidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangePos(Data superData,Vector3 oldV,Vector3 newV)
            {
                if(superData is Data data)
                {

                changePosAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeCharacteruid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeCharacteruidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeBag(Data superData,List<int> oldV,List<int> newV)
            {
                if(superData is Data data)
                {

                changeBagAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeTeam(Data superData,List<int> oldV,List<int> newV)
            {
                if(superData is Data data)
                {

                changeTeamAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeTeamactive(Data superData,List<int> oldV,List<int> newV)
            {
                if(superData is Data data)
                {

                changeTeamactiveAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeUistyleimagename(Data superData,Dictionary<string,string> oldV,Dictionary<string,string> newV)
            {
                if(superData is Data data)
                {

                changeUistyleimagenameAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeCameramode(Data superData,CameraMode oldV,CameraMode newV)
            {
                if(superData is Data data)
                {

                changeCameramodeAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeDialogcache(Data superData,ClipForm.Data oldV,ClipForm.Data newV)
            {
                if(superData is Data data)
                {

                changeDialogcacheAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeBlockprogramuid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeBlockprogramuidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEditorstyle(Data superData,EditorStyle oldV,EditorStyle newV)
            {
                if(superData is Data data)
                {

                changeEditorstyleAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnableequip(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnableequipAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnableskill(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnableskillAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnablefreechangeactiveteamer(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnablefreechangeactiveteamerAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnablefreechangeskill(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnablefreechangeskillAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnableminimap(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnableminimapAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnablelargemap(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnablelargemapAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEnablemission(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeEnablemissionAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLargemap(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeLargemapAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeCurmissionid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeCurmissionidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeTargetscene(Data superData,(int,Vector3) oldV,(int,Vector3) newV)
            {
                if(superData is Data data)
                {

                changeTargetsceneAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeBanscenechange(Data superData,bool oldV,bool newV)
            {
                if(superData is Data data)
                {

                changeBanscenechangeAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeEventstate(Data superData,EventState oldV,EventState newV)
            {
                if(superData is Data data)
                {

                changeEventstateAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
    }
}
        