/* !!!IMPORTANT!!!: This file is a data table file. All code is generated by the table export BAT tool. Do not modify the .cs file directly. Please modify the original Excel file first and then regenerate the code using the tool.*/
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Z_ByteSerialize;
using Z_DesignStyle;
using Z_UnitSystem.Form;
using Z_Text.Form;
using Z_DataSystem.Form;
using Z_Map.Form;
using Z_Map;
using Z_Ui.Form;
using Z_Code.Form;

namespace Form
{

    public static partial class GameCmdDataForm
    {

        

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Register()
        {

                CmdDataForm.childInitAction+=InitInternal;


                CmdDataForm.childRemoveAction+=RemoveChildren;
                CmdDataForm.childAddAction+=AddChildren;
            

            CmdDataForm.changeUidAction+=ChangeUid;

            CmdDataForm.changeNameAction+=ChangeName;

            CmdDataForm.changePrmnamesAction+=ChangePrmnames;

            CmdDataForm.changePrmtypesAction+=ChangePrmtypes;

            CmdDataForm.changeRetnamesAction+=ChangeRetnames;

            CmdDataForm.changeRettypesAction+=ChangeRettypes;

            CmdDataForm.changeDescAction+=ChangeDesc;

            CmdDataForm.changeDefaultcodeAction+=ChangeDefaultcode;

            Z_Json.extra[typeof(Data)]=((obj)=>{
            if(obj is Data data)
                return GetJoByData(data);
            return null;
            },(jo)=>{
            return GetDataByJo(jo);
            });
        }
        
        private static bool inited;

        public static Z_Chain.Chain uidChain =>CmdDataForm.uidChain;

        public static Action<Data> addAction;
        public static Action<Data> removeAction;
        public static Action childInitAction;
        public static Action<Data> childRemoveAction;
        public static Action<Data> childAddAction;
        
        public static Action<Data> beforeGetAction;

        public static Action<Data,int,int> changeUidAction;
                
        public static Action<Data,string,string> changeNameAction;
                
        public static Action<Data,List<string>,List<string>> changePrmnamesAction;
                
        public static Action<Data,List<string>,List<string>> changePrmtypesAction;
                
        public static Action<Data,List<string>,List<string>> changeRetnamesAction;
                
        public static Action<Data,List<string>,List<string>> changeRettypesAction;
                
        public static Action<Data,string,string> changeDescAction;
                
        public static Action<Data,string,string> changeDefaultcodeAction;
                
        public static Action<Data,int,int> changeLabidAction;
                
        public static Action<Data,EditorStyle,EditorStyle> changeLowesteditorstyleAction;
                
        public static Action<Data,string,string> changeAllowasvoidAction;
                


        public partial class Data : CmdDataForm.Data
        {

                    private int  _labId;
                    /// <summary>
                    ///标签
                    ///</summary>
                    public int  labId{
                                get{return _labId;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLabid(this,_labId,value); 
                    }
        
                _labId = value;
                }
                 
                     }
                    
                    private EditorStyle  _lowestEditorStyle;
                    /// <summary>
                    ///最低许可编辑模式
                    ///</summary>
                    public EditorStyle  lowestEditorStyle{
                                get{return _lowestEditorStyle;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLowesteditorstyle(this,_lowestEditorStyle,value); 
                    }
        
                _lowestEditorStyle = value;
                }
                 
                     }
                    
                    private string  _allowAsVoid;
                    /// <summary>
                    ///允许独立声明，使用的语句前缀
                    ///</summary>
                    public string  allowAsVoid{
                                get{return _allowAsVoid;}
 set{

                    if(_DataByUid!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeAllowasvoid(this,_allowAsVoid,value); 
                    }
        
                _allowAsVoid = value;
                }
                 
                     }
                    
            public Data(CmdDataForm.Data data):base(data.uid,data.name,data.prmNames,data.prmTypes,data.retNames,data.retTypes,data.desc,data.defaultCode)
            {
            }
            
            public Data(int uid,string name,List<string> prmNames,List<string> prmTypes,List<string> retNames,List<string> retTypes,string desc,string defaultCode,int labId,EditorStyle lowestEditorStyle,string allowAsVoid):base(uid,name,prmNames,prmTypes,retNames,retTypes,desc,defaultCode)
            {

             this.uid = uid;
             this.name = name;
             this.prmNames = prmNames;
             this.prmTypes = prmTypes;
             this.retNames = retNames;
             this.retTypes = retTypes;
             this.desc = desc;
             this.defaultCode = defaultCode;
             this.labId = labId;
             this.lowestEditorStyle = lowestEditorStyle;
             this.allowAsVoid = allowAsVoid;

            }
            public void Reset(Data data)
            {

             this.uid = data.uid;
             this.name = data.name;
             this.prmNames = data.prmNames;
             this.prmTypes = data.prmTypes;
             this.retNames = data.retNames;
             this.retTypes = data.retTypes;
             this.desc = data.desc;
             this.defaultCode = data.defaultCode;
             this.labId = data.labId;
             this.lowestEditorStyle = data.lowestEditorStyle;
             this.allowAsVoid = data.allowAsVoid;
            }

                public Data Copy(bool sameId = true)
                {
        return new Data(sameId? uid:uidChain.GetId(),name,prmNames==null?new List<string>():new List<string>(prmNames),prmTypes==null?new List<string>():new List<string>(prmTypes),retNames==null?new List<string>():new List<string>(retNames),retTypes==null?new List<string>():new List<string>(retTypes),desc,defaultCode,labId,lowestEditorStyle,allowAsVoid);
                }
            
            public override  void BeforeGet()
            {
                base.BeforeGet();
                GameCmdDataForm.beforeGetAction?.Invoke(this);
            }
        }

                   private static Data _defaultData=new Data(0,"",null,null,null,null,"","",0,default,"");
                   public static Data defaultData=>_defaultData.Copy();


            static HashSet<Data> _DatasHashSet;
            static Dictionary<int, Data> _DataByUid;
            public static Dictionary<int, Data> DataByUid
            {
                get
                {
                    Init();
                    return _DataByUid;
                }
            }
    
            static Dictionary<int, List<Data>> _DatasByLabid;
            public static Dictionary<int, List<Data>> DatasByLabid
            {
                get
                {
                    Init();
                    return _DatasByLabid;
                }
            }
    
            static Dictionary<string, Data> _DataByName;
            public static Dictionary<string, Data> DataByName
            {
                get
                {
                    Init();
                    return _DataByName;
                }
            }
    

        static public void Init()
        {

            CmdDataForm.Init();

        }
        public static void InitInternal()
        {
            if(inited)
                return;
            inited=true;  

        

                _DataByUid = new Dictionary<int, Data>() {

                {100001,new Data(100001,"ShowTip",new List<string>(){"content",},new List<string>(){"string",},null,new List<string>(){"void",},"Show Tip: {0}","ShowTip(\"empty\");",10024,EditorStyle.AvgAdvanced,"")},

                {100002,new Data(100002,"Text",null,null,null,new List<string>(){"string",},"","\"\"",10002,EditorStyle.Avg,"")},

                {100003,new Data(100003,"Num",null,null,null,new List<string>(){"num",},"","1",10002,EditorStyle.AvgAdvanced,"")},

                {100004,new Data(100004,"Image",null,null,null,new List<string>(){"img",},"","\"$i$$i$\"",10002,EditorStyle.Avg,"")},

                {100005,new Data(100005,"Video",null,null,null,new List<string>(){"video",},"","\"$v$$v$\"",10002,EditorStyle.AvgAdvanced,"")},

                {100006,new Data(100006,"Audio",null,null,null,new List<string>(){"audio",},"","\"$a$$a$\"",10002,EditorStyle.AvgAdvanced,"")},

                {100007,new Data(100007,"SceneObjectProto",null,null,null,new List<string>(){"sceneObjectProto",},"","\"$sop$$sop$\"",10002,EditorStyle.AvgAdvanced,"")},

                {100008,new Data(100008,"Item",null,null,null,new List<string>(){"item",},"","\"$it$$it$\"",10002,EditorStyle.AvgAdvanced,"")},

                {100009,new Data(100009,"LocalVar",null,null,null,new List<string>(){"var",},"","a",10006,EditorStyle.AvgAdvanced,"")},

                {100010,new Data(100010,"SetLocalVar",null,null,null,new List<string>(){"void",},"","a = 0;",10006,EditorStyle.AvgAdvanced,"")},

                {100011,new Data(100011,"ShowDialog",new List<string>(){"background","avatar","title","content",},new List<string>(){"img","img","string","string",},null,new List<string>(){"void",},"Show Dialog{1}{2}:{3} bg:{0}","ShowDialog(\"$i$$i$\",\"$i$$i$\",\"empty\",\"empty\");",10022,EditorStyle.Avg,"")},

                {100012,new Data(100012,"ShowDialogWithIllustration",new List<string>(){"background","avatar","title","content","illustration","x","y","scale",},new List<string>(){"img","img","string","string","img","num","num","num",},null,new List<string>(){"void",},"Show Dialog{1}{2}:{3} bg:{0} (illustration:{4} pos x:{5} y:{6} scale:{7})","ShowDialogWithIllustration(\"$i$$i$\",\"$i$$i$\",\"empty\",\"empty\",\"$i$$i$\",0.5,0.5,1)",10022,EditorStyle.AvgAdvanced,"")},

                {100013,new Data(100013,"ShowEffect",new List<string>(){"effect","pos","angle",},new List<string>(){"effect","vector","num",},null,new List<string>(){"void",},"Show Effect{0} {1} , angle{2}","ShowEffect(\"$ef$$ef$\",NewVector(1,1,0),0);",10013,EditorStyle.RpgAdvanced,"")},

                {100014,new Data(100014,"ShowVideo",new List<string>(){"video","loadingBackground",},new List<string>(){"video","img",},null,new List<string>(){"void",},"Show video{0} loading bg:{1}","ShowVideo(\"$v$$v$\",\"$i$$i$\");",10022,EditorStyle.AvgAdvanced,"")},

                {100015,new Data(100015,"ShowImage",new List<string>(){"image","scale","showTime",},new List<string>(){"img","num","num",},new List<string>(){"image",},new List<string>(){"uiImg",},"Show Image:{0} ,scale {1}, last {2} seconds","ShowImage(\"$i$$i$\",1,1)",10023,EditorStyle.Avg,"image = ")},

                {100016,new Data(100016,"ShowImagePermanently",new List<string>(){"image","scale",},new List<string>(){"img","num",},new List<string>(){"image",},new List<string>(){"uiImg",},"Show Image Permanently {0},scale {1}","ShowImagePermanently(\"$i$$i$\",1)",10023,EditorStyle.Avg,"image = ")},

                {100017,new Data(100017,"DeleteImage",new List<string>(){"image","afterTime",},new List<string>(){"uiImg","num",},null,new List<string>(){"void",},"Delete Image {0}  after {1} seconds","DeleteImage(image,1);",10023,EditorStyle.Avg,"")},

                {100018,new Data(100018,"SetImagePosition",new List<string>(){"image","x","y","transitionTime",},new List<string>(){"uiImg","num","num","num",},null,new List<string>(){"void",},"Set Image{0}: x {1} y {2} ,transition takes {3} seconds","SetImagePosition(image,0.5,0.5,1);",10023,EditorStyle.AvgAdvanced,"")},

                {100019,new Data(100019,"SetImageOpacity",new List<string>(){"image","opacity","transitionTime",},new List<string>(){"uiImg","num","num",},null,new List<string>(){"void",},"Set Image{0}: opacity {1},transition takes {2} seconds","SetImageOpacity(image,1,1);",10023,EditorStyle.AvgAdvanced,"")},

                {100020,new Data(100020,"SetImageRotate",new List<string>(){"image","angle","transitionTime",},new List<string>(){"uiImg","num","num",},null,new List<string>(){"void",},"Set Image{0}: angle {1},transition takes {2} seconds","SetImageRotate(image,0,1);",10023,EditorStyle.AvgAdvanced,"")},

                {100021,new Data(100021,"Add",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","1 + 1",10004,EditorStyle.AvgAdvanced,"")},

                {100022,new Data(100022,"Subtract",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","1 - 1",10004,EditorStyle.AvgAdvanced,"")},

                {100023,new Data(100023,"Multiply",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","1 * 1",10004,EditorStyle.AvgAdvanced,"")},

                {100024,new Data(100024,"Divide",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","1 / 1",10004,EditorStyle.AvgAdvanced,"")},

                {100025,new Data(100025,"Wait",new List<string>(){"seconds",},new List<string>(){"num",},null,new List<string>(){"void",},"Wait {0} seconds","Wait(1);",10005,EditorStyle.AvgAdvanced,"")},

                {100026,new Data(100026,"If",null,null,null,new List<string>(){"void",},"","if(1){ }else{ }",10005,EditorStyle.AvgAdvanced,"")},

                {100027,new Data(100027,"For",null,null,null,new List<string>(){"void",},"","for(i=1;i<5;i=i+1){ }",10005,EditorStyle.AvgAdvanced,"")},

                {100028,new Data(100028,"Greater",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","0 > 1",10004,EditorStyle.AvgAdvanced,"")},

                {100029,new Data(100029,"Less",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","0 < 1",10004,EditorStyle.AvgAdvanced,"")},

                {100030,new Data(100030,"Equal",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","0 == 1",10004,EditorStyle.AvgAdvanced,"")},

                {100031,new Data(100031,"NotEqual",new List<string>(){"num","num",},new List<string>(){"num","num",},new List<string>(){"resault",},new List<string>(){"num",},"","0 != 1",10004,EditorStyle.AvgAdvanced,"")},

                {100032,new Data(100032,"Pause",null,null,null,new List<string>(){"void",},"Pause","Pause();",10005,EditorStyle.Rpg,"")},

                {100033,new Data(100033,"Continue",null,null,null,new List<string>(){"void",},"Continue","Continue();",10005,EditorStyle.Rpg,"")},

                {100034,new Data(100034,"GameOver",null,null,null,new List<string>(){"void",},"Game over","GameOver();",10005,EditorStyle.Avg,"")},

                {100035,new Data(100035,"Save",null,null,null,new List<string>(){"void",},"Save","Save();",10005,EditorStyle.Avg,"")},

                {100036,new Data(100036,"Load",null,null,null,new List<string>(){"void",},"Load","Load();",10005,EditorStyle.Avg,"")},

                {100037,new Data(100037,"DestroyObject",new List<string>(){"object",},new List<string>(){"sceneObject",},null,new List<string>(){"void",},"object {0}: Destroy","DestroyObject(self);",10018,EditorStyle.Rpg,"")},

                {100038,new Data(100038,"GenerateObject",new List<string>(){"sceneObject","pos",},new List<string>(){"sceneObjectProto","vector",},new List<string>(){"new Object",},new List<string>(){"sceneObject",},"object {0}: Generate at coordinates({1}):","GenerateObject(\"empty\",NewVector(0,0,0))",10018,EditorStyle.Rpg,"newObject = ")},

                {100039,new Data(100039,"MoveObjectRelative",new List<string>(){"object","pos","transitionTime",},new List<string>(){"sceneObject","vector","num",},null,new List<string>(){"void",},"object {0} : Move to relative coordinates({1}), last {2} seconds","MoveObjectRelative(self,NewVector(1,1,0),1);",10019,EditorStyle.Rpg,"")},

                {100040,new Data(100040,"MoveObject",new List<string>(){"object","pos","transitionTime",},new List<string>(){"sceneObject","vector","num",},null,new List<string>(){"void",},"object {0} : Move to absolute coordinates({1}), last {2} seconds","MoveObject(self,NewVector(1,1,0),1);",10019,EditorStyle.Rpg,"")},

                {100041,new Data(100041,"GainItem",new List<string>(){"item","amount",},new List<string>(){"item","num",},null,new List<string>(){"void",},"Gain {0} x {1}","GainItem(\"empty\",1);",10014,EditorStyle.Rpg,"")},

                {100042,new Data(100042,"LostItem",new List<string>(){"item","amount",},new List<string>(){"item","num",},null,new List<string>(){"void",},"Lost {0} x {1}","LostItem(\"empty\",1);",10014,EditorStyle.Rpg,"")},

                {100043,new Data(100043,"SetCharacterParameter",new List<string>(){"character","paramName","value",},new List<string>(){"character","string","var",},null,new List<string>(){"void",},"Set Character {0} 's {1} = {2}","SetCharacterParameter(self,\"empty\",1);",10009,EditorStyle.Rpg,"")},

                {100044,new Data(100044,"GetCurrentCharacter",null,null,new List<string>(){"character",},new List<string>(){"character",},"Get currently used character","GetCurrentCharacter()",10011,EditorStyle.Rpg,"")},

                {100045,new Data(100045,"MoveCharacterRelative",new List<string>(){"character","pos","transitionTime",},new List<string>(){"character","vector","num",},null,new List<string>(){"void",},"character {0} : Move to relative coordinates({1}),last {2} seconds","MoveCharacterRelative(self,NewVector(1,1,0),1);",10012,EditorStyle.RpgAdvanced,"")},

                {100046,new Data(100046,"MoveCharacter",new List<string>(){"character","pos","transitionTime",},new List<string>(){"character","vector","num",},null,new List<string>(){"void",},"character {0} : Move to absolute coordinates({1}),last {2} seconds","MoveCharacter(self,NewVector(1,1,0),1);",10012,EditorStyle.RpgAdvanced,"")},

                {100047,new Data(100047,"SetCharacterNavigateRelative",new List<string>(){"character","pos",},new List<string>(){"num","vector",},null,new List<string>(){"void",},"character {0} : Navigate to relative coordinates({1})","SetCharacterNavigateRelative(self,NewVector(1,1,0));",10012,EditorStyle.RpgAdvanced,"")},

                {100048,new Data(100048,"SetCharacterNavigate",new List<string>(){"character","pos",},new List<string>(){"num","vector",},null,new List<string>(){"void",},"character {0} : Navigate to absolute coordinates({1})","SetCharacterNavigate(self,NewVector(1,1,0));",10012,EditorStyle.RpgAdvanced,"")},

                {100049,new Data(100049,"GetCharacterPosition",new List<string>(){"character",},new List<string>(){"character",},new List<string>(){"pos",},new List<string>(){"vector",},"character {0} position","GetCharacterPosition(self)",10012,EditorStyle.RpgAdvanced,"")},

                {100050,new Data(100050,"NewVector",new List<string>(){"x","y","height",},new List<string>(){"num","num","num",},new List<string>(){"vector",},new List<string>(){"vector",},"vector({0},{1},{2})","NewVector(0,0,0)",10002,EditorStyle.RpgAdvanced,"")},

                {100051,new Data(100051,"StopCharacterNavigate",new List<string>(){"character",},new List<string>(){"character",},null,new List<string>(){"void",},"character {0} : Navigate stop","StopCharacterNavigate(self)",10012,EditorStyle.RpgAdvanced,"")},

                {100052,new Data(100052,"SetCharacterPositionRelative",new List<string>(){"character","pos",},new List<string>(){"character","vector",},null,new List<string>(){"void",},"character {0} : Set relative position ({1})","SetCharacterPositionRelative(self,NewVector(1,1,0));",10012,EditorStyle.RpgAdvanced,"")},

                {100053,new Data(100053,"SetCharacterPosition",new List<string>(){"character","pos",},new List<string>(){"character","vector",},null,new List<string>(){"void",},"character {0} : Set absolute position ({1})","SetCharacterPosition(self,NewVector(1,1,0));",10012,EditorStyle.RpgAdvanced,"")},

                {100054,new Data(100054,"GetCharacterParameter",new List<string>(){"character","paramName",},new List<string>(){"character","string",},new List<string>(){"value",},new List<string>(){"var",},"Get Character {0} 's {1}","GetCharacterParameter(self,\"empty\")",10009,EditorStyle.Rpg,"")},

                {100055,new Data(100055,"SelfSceneObject",null,null,null,new List<string>(){"sceneObject",},"","self",10018,EditorStyle.Rpg,"")},

                {100056,new Data(100056,"TriggerTargetSceneObject",null,null,null,new List<string>(){"sceneObject",},"","target",10018,EditorStyle.Rpg,"")},

                {100057,new Data(100057,"SelfCharacter",null,null,null,new List<string>(){"character",},"","self",10011,EditorStyle.Rpg,"")},

                {100058,new Data(100058,"TriggerTargetCharacter",null,null,null,new List<string>(){"character",},"","target",10011,EditorStyle.Rpg,"")},

                {100059,new Data(100059,"Return",new List<string>(){"result",},new List<string>(){"var",},null,new List<string>(){"void",},"return {0}","Return result;",10005,EditorStyle.Avg,"")},

                {100060,new Data(100060,"GetSceneObjectParameter",new List<string>(){"sceneObject","paramName",},new List<string>(){"sceneObject","string",},new List<string>(){"value",},new List<string>(){"var",},"Get scene object {0} 's {1}","GetSceneObjectParameter(self,\"empty\")",10017,EditorStyle.Rpg,"")},

                {100061,new Data(100061,"SetSceneObjectParameter",new List<string>(){"sceneObject","paramName","value",},new List<string>(){"sceneObject","string","var",},null,new List<string>(){"void",},"Set scene object {0} 's {1} = {2}","SetSceneObjectParameter(self,\"empty\",1);",10017,EditorStyle.Rpg,"")},

                {100062,new Data(100062,"GetCharacterRotation",new List<string>(){"character",},new List<string>(){"character",},new List<string>(){"angle",},new List<string>(){"num",},"character {0} rotation","GetCharacterRotation(self)",10012,EditorStyle.Rpg,"")},

                {100063,new Data(100063,"SetCharacterRotation",new List<string>(){"character","angle","transitionTime",},new List<string>(){"character","num","num",},null,new List<string>(){"void",},"Set character {0} rotation ={1}","SetCharacterRotation(self,180,0);",10012,EditorStyle.Rpg,"")},

                {100064,new Data(100064,"GetCharacterForwardVector",new List<string>(){"character",},new List<string>(){"character",},new List<string>(){"direction",},new List<string>(){"vector",},"character {0} forward vector","GetCharacterForwardVector(self)",10012,EditorStyle.Rpg,"")},

                {100065,new Data(100065,"GetObjectRotation",new List<string>(){"sceneObject",},new List<string>(){"sceneObject",},new List<string>(){"angle",},new List<string>(){"num",},"scene object {0} rotation","GetObjectRotation(self)",10019,EditorStyle.Rpg,"")},

                {100066,new Data(100066,"SetObjectRotation",new List<string>(){"sceneObject","angle","transitionTime",},new List<string>(){"sceneObject","num","num",},null,new List<string>(){"void",},"Set scene object {0} rotation ={1}, last {2} seconds","SetObjectRotation(self,180,0);",10019,EditorStyle.Rpg,"")},

                {100067,new Data(100067,"GetObjectForwardVector",new List<string>(){"sceneObject",},new List<string>(){"sceneObject",},new List<string>(){"direction",},new List<string>(){"vector",},"scene Object {0} forward vector","GetObjectForwardVector(self)",10019,EditorStyle.Rpg,"")},

                {100068,new Data(100068,"IsObjectEnableCollision",new List<string>(){"sceneObject",},new List<string>(){"sceneObject",},new List<string>(){"enabled",},new List<string>(){"num",},"scene Object {0} collision is enabled?","IsObjectEnableCollision(self)",10018,EditorStyle.Rpg,"")},

                {100069,new Data(100069,"GetCharacterRightVector",new List<string>(){"character",},new List<string>(){"character",},new List<string>(){"direction",},new List<string>(){"vector",},"character {0} right vector","GetCharacterRightVector(self)",10012,EditorStyle.Rpg,"")},

                {100070,new Data(100070,"GetObjectRightVector",new List<string>(){"sceneObject",},new List<string>(){"sceneObject",},new List<string>(){"direction",},new List<string>(){"vector",},"scene Object {0} right vector","GetObjectRightVector(self)",10019,EditorStyle.Rpg,"")},

                {100071,new Data(100071,"IsObjectActive",new List<string>(){"sceneObject",},new List<string>(){"sceneObject",},new List<string>(){"active",},new List<string>(){"num",},"scene Object {0} is active?","IsObjectActive(self)",10018,EditorStyle.Rpg,"")},

                {100072,new Data(100072,"IsCharacterActive",new List<string>(){"character",},new List<string>(){"character",},new List<string>(){"active",},new List<string>(){"num",},"character {0} is active?","IsCharacterActive(self)",10012,EditorStyle.Rpg,"")},

                {100073,new Data(100073,"ChangeBgm",new List<string>(){"bgm",},new List<string>(){"audio",},null,new List<string>(){"void",},"Bgm change to {0}","ChangeBgm(\"$a$$a$\");",10001,EditorStyle.Avg,"")},

                {100074,new Data(100074,"CharacterPlayAnim",new List<string>(){"character","animName",},new List<string>(){"character","string",},null,new List<string>(){"void",},"Character {0} Play animation: {1}","CharacterPlayAnim(self,\"empty\");",10007,EditorStyle.Rpg,"")},

                {100075,new Data(100075,"CharacterStun",new List<string>(){"character","time",},new List<string>(){"character","num",},null,new List<string>(){"void",},"Character {0} stun {1} s","CharacterStun(self,1);",10007,EditorStyle.Rpg,"")},

                {100076,new Data(100076,"GetSkillParameter",new List<string>(){"skill","paramName",},new List<string>(){"skill","string",},new List<string>(){"value",},new List<string>(){"var",},"Get skill {0} 's {1}","GetSkillParameter(self,\"empty\")",10020,EditorStyle.Rpg,"")},

                {100077,new Data(100077,"SetSkillParameter",new List<string>(){"skill","paramName","value",},new List<string>(){"skill","string","var",},null,new List<string>(){"void",},"Set skill {0} 's {1} = {2}","SetSkillParameter(self,\"empty\",1);",10020,EditorStyle.Rpg,"")},

                {100078,new Data(100078,"TargetSkill",null,null,null,new List<string>(){"skill",},"","target",10021,EditorStyle.Rpg,"")},

                {100079,new Data(100079,"Effect",null,null,null,new List<string>(){"effect",},"","\"$ef$$ef$\"",10002,EditorStyle.Rpg,"")},

                {100080,new Data(100080,"ParameterDelta",null,null,null,new List<string>(){"var",},"","delta",10009,EditorStyle.Rpg,"")},

                {100081,new Data(100081,"FloatingText",new List<string>(){"content","pos",},new List<string>(){"string","vector",},null,new List<string>(){"void",},"Floating text: {0} at pos {1}","FloatingText(\"empty\",NewVector(1,1,0));",10024,EditorStyle.Rpg,"")},

                {100082,new Data(100082,"UseSkill",new List<string>(){"character","skill","ignoreCd",},new List<string>(){"character","skill","num",},null,new List<string>(){"void",},"Character {0} use skill {1},ignoreCd? {2}","UseSkill(self,\"$sk$$sk$\",0);",10010,EditorStyle.Rpg,"")},

                {100083,new Data(100083,"Skill",null,null,null,new List<string>(){"skill",},"","\"$sk$$sk$\"",10002,EditorStyle.Rpg,"")},

                {100084,new Data(100084,"PlayAudio",new List<string>(){"audio",},new List<string>(){"audio",},null,new List<string>(){"void",},"Play {0}","PlayAudio(\"$a$$a$\");",10001,EditorStyle.Rpg,"")},

                {100085,new Data(100085,"GetCharactersInArea",new List<string>(){"pos","radius",},new List<string>(){"vector","num",},new List<string>(){"list",},new List<string>(){"var",},"characters in position {0} ,radius {1}","GetCharactersInArea(NewVector(1,1,0),5);",10008,EditorStyle.Rpg,"")},

                {100086,new Data(100086,"GetLength",null,null,null,null,"","Len(a)",10003,EditorStyle.Rpg,"")},

                {100087,new Data(100087,"GetVarKeys",null,null,null,null,"","GetKeys(a)",10003,EditorStyle.Rpg,"")},

                {100088,new Data(100088,"GetVarValues",null,null,null,null,"","GetValues(a)",10003,EditorStyle.Rpg,"")},

                {100089,new Data(100089,"GetLookAtRotation",new List<string>(){"pos","pos",},new List<string>(){"vector","vector",},new List<string>(){"angle",},new List<string>(){"num",},"Get rotation of pos {0} look at {1}","GetLookAtRotation(NewVector(1,1,0),NewVector(1,1,0))",10004,EditorStyle.Rpg,"")},

                {100090,new Data(100090,"GetObjectPosition",new List<string>(){"sceneObject",},new List<string>(){"sceneObject",},new List<string>(){"pos",},new List<string>(){"vector",},"scene Object {0} position","GetObjectPosition(self)",10019,EditorStyle.Rpg,"")},

                {100091,new Data(100091,"GetNormalizedVector",new List<string>(){"vector",},new List<string>(){"vector",},new List<string>(){"vector",},new List<string>(){"vector",},"Get Normalized {0}","GetNormalizedVector(NewVector(1,1,0))",10004,EditorStyle.Rpg,"")},

                {100092,new Data(100092,"SetObjectPosition",new List<string>(){"sceneObject","pos",},new List<string>(){"sceneObject","vector",},null,new List<string>(){"void",},"scene Object {0} : Set absolute position ({1})","SetObjectPosition(self,NewVector(1,1,0));",10012,EditorStyle.Rpg,"")},

                {100093,new Data(100093,"IsUnobstructed",new List<string>(){"from","to","radius",},new List<string>(){"vector","vector","num",},new List<string>(){"unobstructed",},new List<string>(){"num",},"sphere with {2} radius from {0} to {1} is unobstructed(collidable object)","IsUnobstructed(NewVector(1,1,0),NewVector(1,1,0),0.2)",10016,EditorStyle.Rpg,"")},

                {100094,new Data(100094,"ShowEffectByCharacter",new List<string>(){"effect","character","ignoreRotation",},new List<string>(){"effect","character","num",},null,new List<string>(){"void",},"Show character:{1} Effect{0} ignore rotation?{2} ","ShowEffectByCharacter(\"$ef$$ef$\",self,1);",10013,EditorStyle.RpgAdvanced,"")},

                {100095,new Data(100095,"GetVectorByRotation",new List<string>(){"rotation",},new List<string>(){"num",},new List<string>(){"vector",},new List<string>(){"vector",},"Get Vector By Rotation {0}","GetVectorByRotation(0)",10004,EditorStyle.Rpg,"")},

                {100096,new Data(100096,"DestroyCharacter",new List<string>(){"character",},new List<string>(){"character",},null,new List<string>(){"void",},"character {0}: Destroy","DestroyCharacter(self);",10011,EditorStyle.Rpg,"")},

                {100097,new Data(100097,"MakeChoice",new List<string>(){"options",},new List<string>(){"var",},new List<string>(){"resault",},new List<string>(){"var",},"Make choice from {0}","MakeChoice(options)",10025,EditorStyle.AvgAdvanced,"res=")},

                {100098,new Data(100098,"ShowDialogWithChoice",new List<string>(){"background","avatar","title","content","options",},new List<string>(){"img","img","string","string","var",},new List<string>(){"resault",},new List<string>(){"var",},"Show Dialog{1}{2}:{3} bg:{0},with choice{4}","ShowDialogWithChoice(\"$i$$i$\",\"$i$$i$\",\"empty\",\"empty\",options);",10022,EditorStyle.AvgAdvanced,"")},

                {100099,new Data(100099,"CharacterChat",new List<string>(){"character","content","icon","showTime",},new List<string>(){"character","string","img","num",},null,new List<string>(){"void",},"Character {0} img:{2},chat:{1},last {4} times","CharacterChat(self,\"empty\",\"$i$$i$\",3);",10022,EditorStyle.Rpg,"")},

                {100100,new Data(100100,"IsMissionAdded",new List<string>(){"missionName",},new List<string>(){"string",},new List<string>(){"added",},new List<string>(){"num",},"Mission {0} is added?","IsMissionAdded(\"empty\")",10015,EditorStyle.Rpg,"")},

                {100101,new Data(100101,"HasMissionDone",new List<string>(){"missionName",},new List<string>(){"string",},new List<string>(){"done",},new List<string>(){"num",},"Mission {0} has done?","HasMissionDone(\"empty\")",10015,EditorStyle.Rpg,"")},

                {100102,new Data(100102,"AddMission",new List<string>(){"missionName",},new List<string>(){"string",},null,new List<string>(){"void",},"Add mission {0}","MissionAdd(\"empty\");",10015,EditorStyle.Rpg,"")},

                {100103,new Data(100103,"DoneMission",new List<string>(){"missionName",},new List<string>(){"string",},null,new List<string>(){"void",},"Done mission {0}","MissionDone(\"empty\");",10015,EditorStyle.Rpg,"")},

                {100104,new Data(100104,"MoveToScene",new List<string>(){"sceneName","pos",},new List<string>(){"string","vector",},null,new List<string>(){"void",},"Move to Scene {0} position: {1}","MoveToScene(\"empty\",NewVector(1,1,0));",10005,EditorStyle.AvgAdvanced,"")},

                {100105,new Data(100105,"ShowTeamerSelect",null,null,null,new List<string>(){"void",},"Show Teamer Select","ShowTeamerSelect()",10025,EditorStyle.AvgAdvanced,"")},

                {100106,new Data(100106,"GetVectorLength",new List<string>(){"vector",},new List<string>(){"vector",},new List<string>(){"length",},new List<string>(){"num",},"Vector {0}'s Length","GetVectorLength(NewVector(0,0,0))",10004,EditorStyle.Rpg,"")},

                };
                _DatasHashSet=new HashSet<Data>();
                
                    _DataByName = new Dictionary<string, Data>() {
    
                        {"ShowTip",_DataByUid[100001]},
    
                        {"Text",_DataByUid[100002]},
    
                        {"Num",_DataByUid[100003]},
    
                        {"Image",_DataByUid[100004]},
    
                        {"Video",_DataByUid[100005]},
    
                        {"Audio",_DataByUid[100006]},
    
                        {"SceneObjectProto",_DataByUid[100007]},
    
                        {"Item",_DataByUid[100008]},
    
                        {"LocalVar",_DataByUid[100009]},
    
                        {"SetLocalVar",_DataByUid[100010]},
    
                        {"ShowDialog",_DataByUid[100011]},
    
                        {"ShowDialogWithIllustration",_DataByUid[100012]},
    
                        {"ShowEffect",_DataByUid[100013]},
    
                        {"ShowVideo",_DataByUid[100014]},
    
                        {"ShowImage",_DataByUid[100015]},
    
                        {"ShowImagePermanently",_DataByUid[100016]},
    
                        {"DeleteImage",_DataByUid[100017]},
    
                        {"SetImagePosition",_DataByUid[100018]},
    
                        {"SetImageOpacity",_DataByUid[100019]},
    
                        {"SetImageRotate",_DataByUid[100020]},
    
                        {"Add",_DataByUid[100021]},
    
                        {"Subtract",_DataByUid[100022]},
    
                        {"Multiply",_DataByUid[100023]},
    
                        {"Divide",_DataByUid[100024]},
    
                        {"Wait",_DataByUid[100025]},
    
                        {"If",_DataByUid[100026]},
    
                        {"For",_DataByUid[100027]},
    
                        {"Greater",_DataByUid[100028]},
    
                        {"Less",_DataByUid[100029]},
    
                        {"Equal",_DataByUid[100030]},
    
                        {"NotEqual",_DataByUid[100031]},
    
                        {"Pause",_DataByUid[100032]},
    
                        {"Continue",_DataByUid[100033]},
    
                        {"GameOver",_DataByUid[100034]},
    
                        {"Save",_DataByUid[100035]},
    
                        {"Load",_DataByUid[100036]},
    
                        {"DestroyObject",_DataByUid[100037]},
    
                        {"GenerateObject",_DataByUid[100038]},
    
                        {"MoveObjectRelative",_DataByUid[100039]},
    
                        {"MoveObject",_DataByUid[100040]},
    
                        {"GainItem",_DataByUid[100041]},
    
                        {"LostItem",_DataByUid[100042]},
    
                        {"SetCharacterParameter",_DataByUid[100043]},
    
                        {"GetCurrentCharacter",_DataByUid[100044]},
    
                        {"MoveCharacterRelative",_DataByUid[100045]},
    
                        {"MoveCharacter",_DataByUid[100046]},
    
                        {"SetCharacterNavigateRelative",_DataByUid[100047]},
    
                        {"SetCharacterNavigate",_DataByUid[100048]},
    
                        {"GetCharacterPosition",_DataByUid[100049]},
    
                        {"NewVector",_DataByUid[100050]},
    
                        {"StopCharacterNavigate",_DataByUid[100051]},
    
                        {"SetCharacterPositionRelative",_DataByUid[100052]},
    
                        {"SetCharacterPosition",_DataByUid[100053]},
    
                        {"GetCharacterParameter",_DataByUid[100054]},
    
                        {"SelfSceneObject",_DataByUid[100055]},
    
                        {"TriggerTargetSceneObject",_DataByUid[100056]},
    
                        {"SelfCharacter",_DataByUid[100057]},
    
                        {"TriggerTargetCharacter",_DataByUid[100058]},
    
                        {"Return",_DataByUid[100059]},
    
                        {"GetSceneObjectParameter",_DataByUid[100060]},
    
                        {"SetSceneObjectParameter",_DataByUid[100061]},
    
                        {"GetCharacterRotation",_DataByUid[100062]},
    
                        {"SetCharacterRotation",_DataByUid[100063]},
    
                        {"GetCharacterForwardVector",_DataByUid[100064]},
    
                        {"GetObjectRotation",_DataByUid[100065]},
    
                        {"SetObjectRotation",_DataByUid[100066]},
    
                        {"GetObjectForwardVector",_DataByUid[100067]},
    
                        {"IsObjectEnableCollision",_DataByUid[100068]},
    
                        {"GetCharacterRightVector",_DataByUid[100069]},
    
                        {"GetObjectRightVector",_DataByUid[100070]},
    
                        {"IsObjectActive",_DataByUid[100071]},
    
                        {"IsCharacterActive",_DataByUid[100072]},
    
                        {"ChangeBgm",_DataByUid[100073]},
    
                        {"CharacterPlayAnim",_DataByUid[100074]},
    
                        {"CharacterStun",_DataByUid[100075]},
    
                        {"GetSkillParameter",_DataByUid[100076]},
    
                        {"SetSkillParameter",_DataByUid[100077]},
    
                        {"TargetSkill",_DataByUid[100078]},
    
                        {"Effect",_DataByUid[100079]},
    
                        {"ParameterDelta",_DataByUid[100080]},
    
                        {"FloatingText",_DataByUid[100081]},
    
                        {"UseSkill",_DataByUid[100082]},
    
                        {"Skill",_DataByUid[100083]},
    
                        {"PlayAudio",_DataByUid[100084]},
    
                        {"GetCharactersInArea",_DataByUid[100085]},
    
                        {"GetLength",_DataByUid[100086]},
    
                        {"GetVarKeys",_DataByUid[100087]},
    
                        {"GetVarValues",_DataByUid[100088]},
    
                        {"GetLookAtRotation",_DataByUid[100089]},
    
                        {"GetObjectPosition",_DataByUid[100090]},
    
                        {"GetNormalizedVector",_DataByUid[100091]},
    
                        {"SetObjectPosition",_DataByUid[100092]},
    
                        {"IsUnobstructed",_DataByUid[100093]},
    
                        {"ShowEffectByCharacter",_DataByUid[100094]},
    
                        {"GetVectorByRotation",_DataByUid[100095]},
    
                        {"DestroyCharacter",_DataByUid[100096]},
    
                        {"MakeChoice",_DataByUid[100097]},
    
                        {"ShowDialogWithChoice",_DataByUid[100098]},
    
                        {"CharacterChat",_DataByUid[100099]},
    
                        {"IsMissionAdded",_DataByUid[100100]},
    
                        {"HasMissionDone",_DataByUid[100101]},
    
                        {"AddMission",_DataByUid[100102]},
    
                        {"DoneMission",_DataByUid[100103]},
    
                        {"MoveToScene",_DataByUid[100104]},
    
                        {"ShowTeamerSelect",_DataByUid[100105]},
    
                        {"GetVectorLength",_DataByUid[100106]},
    
                    
                    };
                    foreach(var v in _DataByUid.Values)
                    {
                        _DatasHashSet.Add(v);
                    }
    
                    _DatasByLabid = new Dictionary<int, List<Data>>() {
    
                            {10024,new List<Data>()},
        
                            {10002,new List<Data>()},
        
                            {10006,new List<Data>()},
        
                            {10022,new List<Data>()},
        
                            {10013,new List<Data>()},
        
                            {10023,new List<Data>()},
        
                            {10004,new List<Data>()},
        
                            {10005,new List<Data>()},
        
                            {10018,new List<Data>()},
        
                            {10019,new List<Data>()},
        
                            {10014,new List<Data>()},
        
                            {10009,new List<Data>()},
        
                            {10011,new List<Data>()},
        
                            {10012,new List<Data>()},
        
                            {10017,new List<Data>()},
        
                            {10001,new List<Data>()},
        
                            {10007,new List<Data>()},
        
                            {10020,new List<Data>()},
        
                            {10021,new List<Data>()},
        
                            {10010,new List<Data>()},
        
                            {10008,new List<Data>()},
        
                            {10003,new List<Data>()},
        
                            {10016,new List<Data>()},
        
                            {10025,new List<Data>()},
        
                            {10015,new List<Data>()},
        
                };

                    _DatasByLabid[10024].Add(_DataByUid[100001]);

                    _DatasByLabid[10002].Add(_DataByUid[100002]);

                    _DatasByLabid[10002].Add(_DataByUid[100003]);

                    _DatasByLabid[10002].Add(_DataByUid[100004]);

                    _DatasByLabid[10002].Add(_DataByUid[100005]);

                    _DatasByLabid[10002].Add(_DataByUid[100006]);

                    _DatasByLabid[10002].Add(_DataByUid[100007]);

                    _DatasByLabid[10002].Add(_DataByUid[100008]);

                    _DatasByLabid[10006].Add(_DataByUid[100009]);

                    _DatasByLabid[10006].Add(_DataByUid[100010]);

                    _DatasByLabid[10022].Add(_DataByUid[100011]);

                    _DatasByLabid[10022].Add(_DataByUid[100012]);

                    _DatasByLabid[10013].Add(_DataByUid[100013]);

                    _DatasByLabid[10022].Add(_DataByUid[100014]);

                    _DatasByLabid[10023].Add(_DataByUid[100015]);

                    _DatasByLabid[10023].Add(_DataByUid[100016]);

                    _DatasByLabid[10023].Add(_DataByUid[100017]);

                    _DatasByLabid[10023].Add(_DataByUid[100018]);

                    _DatasByLabid[10023].Add(_DataByUid[100019]);

                    _DatasByLabid[10023].Add(_DataByUid[100020]);

                    _DatasByLabid[10004].Add(_DataByUid[100021]);

                    _DatasByLabid[10004].Add(_DataByUid[100022]);

                    _DatasByLabid[10004].Add(_DataByUid[100023]);

                    _DatasByLabid[10004].Add(_DataByUid[100024]);

                    _DatasByLabid[10005].Add(_DataByUid[100025]);

                    _DatasByLabid[10005].Add(_DataByUid[100026]);

                    _DatasByLabid[10005].Add(_DataByUid[100027]);

                    _DatasByLabid[10004].Add(_DataByUid[100028]);

                    _DatasByLabid[10004].Add(_DataByUid[100029]);

                    _DatasByLabid[10004].Add(_DataByUid[100030]);

                    _DatasByLabid[10004].Add(_DataByUid[100031]);

                    _DatasByLabid[10005].Add(_DataByUid[100032]);

                    _DatasByLabid[10005].Add(_DataByUid[100033]);

                    _DatasByLabid[10005].Add(_DataByUid[100034]);

                    _DatasByLabid[10005].Add(_DataByUid[100035]);

                    _DatasByLabid[10005].Add(_DataByUid[100036]);

                    _DatasByLabid[10018].Add(_DataByUid[100037]);

                    _DatasByLabid[10018].Add(_DataByUid[100038]);

                    _DatasByLabid[10019].Add(_DataByUid[100039]);

                    _DatasByLabid[10019].Add(_DataByUid[100040]);

                    _DatasByLabid[10014].Add(_DataByUid[100041]);

                    _DatasByLabid[10014].Add(_DataByUid[100042]);

                    _DatasByLabid[10009].Add(_DataByUid[100043]);

                    _DatasByLabid[10011].Add(_DataByUid[100044]);

                    _DatasByLabid[10012].Add(_DataByUid[100045]);

                    _DatasByLabid[10012].Add(_DataByUid[100046]);

                    _DatasByLabid[10012].Add(_DataByUid[100047]);

                    _DatasByLabid[10012].Add(_DataByUid[100048]);

                    _DatasByLabid[10012].Add(_DataByUid[100049]);

                    _DatasByLabid[10002].Add(_DataByUid[100050]);

                    _DatasByLabid[10012].Add(_DataByUid[100051]);

                    _DatasByLabid[10012].Add(_DataByUid[100052]);

                    _DatasByLabid[10012].Add(_DataByUid[100053]);

                    _DatasByLabid[10009].Add(_DataByUid[100054]);

                    _DatasByLabid[10018].Add(_DataByUid[100055]);

                    _DatasByLabid[10018].Add(_DataByUid[100056]);

                    _DatasByLabid[10011].Add(_DataByUid[100057]);

                    _DatasByLabid[10011].Add(_DataByUid[100058]);

                    _DatasByLabid[10005].Add(_DataByUid[100059]);

                    _DatasByLabid[10017].Add(_DataByUid[100060]);

                    _DatasByLabid[10017].Add(_DataByUid[100061]);

                    _DatasByLabid[10012].Add(_DataByUid[100062]);

                    _DatasByLabid[10012].Add(_DataByUid[100063]);

                    _DatasByLabid[10012].Add(_DataByUid[100064]);

                    _DatasByLabid[10019].Add(_DataByUid[100065]);

                    _DatasByLabid[10019].Add(_DataByUid[100066]);

                    _DatasByLabid[10019].Add(_DataByUid[100067]);

                    _DatasByLabid[10018].Add(_DataByUid[100068]);

                    _DatasByLabid[10012].Add(_DataByUid[100069]);

                    _DatasByLabid[10019].Add(_DataByUid[100070]);

                    _DatasByLabid[10018].Add(_DataByUid[100071]);

                    _DatasByLabid[10012].Add(_DataByUid[100072]);

                    _DatasByLabid[10001].Add(_DataByUid[100073]);

                    _DatasByLabid[10007].Add(_DataByUid[100074]);

                    _DatasByLabid[10007].Add(_DataByUid[100075]);

                    _DatasByLabid[10020].Add(_DataByUid[100076]);

                    _DatasByLabid[10020].Add(_DataByUid[100077]);

                    _DatasByLabid[10021].Add(_DataByUid[100078]);

                    _DatasByLabid[10002].Add(_DataByUid[100079]);

                    _DatasByLabid[10009].Add(_DataByUid[100080]);

                    _DatasByLabid[10024].Add(_DataByUid[100081]);

                    _DatasByLabid[10010].Add(_DataByUid[100082]);

                    _DatasByLabid[10002].Add(_DataByUid[100083]);

                    _DatasByLabid[10001].Add(_DataByUid[100084]);

                    _DatasByLabid[10008].Add(_DataByUid[100085]);

                    _DatasByLabid[10003].Add(_DataByUid[100086]);

                    _DatasByLabid[10003].Add(_DataByUid[100087]);

                    _DatasByLabid[10003].Add(_DataByUid[100088]);

                    _DatasByLabid[10004].Add(_DataByUid[100089]);

                    _DatasByLabid[10019].Add(_DataByUid[100090]);

                    _DatasByLabid[10004].Add(_DataByUid[100091]);

                    _DatasByLabid[10012].Add(_DataByUid[100092]);

                    _DatasByLabid[10016].Add(_DataByUid[100093]);

                    _DatasByLabid[10013].Add(_DataByUid[100094]);

                    _DatasByLabid[10004].Add(_DataByUid[100095]);

                    _DatasByLabid[10011].Add(_DataByUid[100096]);

                    _DatasByLabid[10025].Add(_DataByUid[100097]);

                    _DatasByLabid[10022].Add(_DataByUid[100098]);

                    _DatasByLabid[10022].Add(_DataByUid[100099]);

                    _DatasByLabid[10015].Add(_DataByUid[100100]);

                    _DatasByLabid[10015].Add(_DataByUid[100101]);

                    _DatasByLabid[10015].Add(_DataByUid[100102]);

                    _DatasByLabid[10015].Add(_DataByUid[100103]);

                    _DatasByLabid[10005].Add(_DataByUid[100104]);

                    _DatasByLabid[10025].Add(_DataByUid[100105]);

                    _DatasByLabid[10004].Add(_DataByUid[100106]);


            childInitAction?.Invoke();
            

            foreach(var data in DataByUid.Values)
            {
                CmdDataForm.AddData(data);
            }


        
             
        }


        public static List<Data> GetDatasByJa(JArray ja)
        {
            Init();
            List<Data> lst=new List<Data>();
            foreach(JObject jo in ja)
            {
                if(jo.Get<int>("uid")==0)
                    continue;
                lst.Add(GetDataByJo(jo));
            }
            return lst;
        }

        public static JArray GetJaByDatas()
        {
            Init();
            JArray ja=new JArray();
            foreach(Data data in _DataByUid.Values)
            {
                if(data.uid==0)
                    continue;
                ja.Add(GetJoByData(data));
            }
            return ja;
        }

        public static Data GetDataByJo(JObject jo)
        {
            Init();

            Data data=new Data(

                jo.SelectToken("uid")==null?defaultData.uid:jo.Get<int>("uid"),

                jo.SelectToken("name")==null?defaultData.name:jo.Get<string>("name"),

                jo.SelectToken("prmNames")==null?defaultData.prmNames:jo.Get<List<string>>("prmNames"),

                jo.SelectToken("prmTypes")==null?defaultData.prmTypes:jo.Get<List<string>>("prmTypes"),

                jo.SelectToken("retNames")==null?defaultData.retNames:jo.Get<List<string>>("retNames"),

                jo.SelectToken("retTypes")==null?defaultData.retTypes:jo.Get<List<string>>("retTypes"),

                jo.SelectToken("desc")==null?defaultData.desc:jo.Get<string>("desc"),

                jo.SelectToken("defaultCode")==null?defaultData.defaultCode:jo.Get<string>("defaultCode"),

                jo.SelectToken("labId")==null?defaultData.labId:jo.Get<int>("labId"),

                jo.SelectToken("lowestEditorStyle")==null?defaultData.lowestEditorStyle:jo.Get<EditorStyle>("lowestEditorStyle"),

                jo.SelectToken("allowAsVoid")==null?defaultData.allowAsVoid:jo.Get<string>("allowAsVoid")
                    );

            return data;
        }

        public static JObject GetJoByData(Data data)
        {
            Init();
            data.BeforeGet();

            JObject jo=new JObject();

            jo.Set<int>("uid",data.uid);

            jo.Set<string>("name",data.name);

            jo.Set<List<string>>("prmNames",data.prmNames);

            jo.Set<List<string>>("prmTypes",data.prmTypes);

            jo.Set<List<string>>("retNames",data.retNames);

            jo.Set<List<string>>("retTypes",data.retTypes);

            jo.Set<string>("desc",data.desc);

            jo.Set<string>("defaultCode",data.defaultCode);

            jo.Set<int>("labId",data.labId);

            jo.Set<EditorStyle>("lowestEditorStyle",data.lowestEditorStyle);

            jo.Set<string>("allowAsVoid",data.allowAsVoid);

            return jo;
        }


        public static int AddData(Data data)
        {
            Init();
            if(DataByUid.ContainsKey(data.uid))
                return data.uid;
            if(data.uid==-1)
            { 
                int uid=uidChain.GetId();
                if(uid==-1)
                    return -1;
                data.uid=uid;  
            }
            uidChain.PopId(data.uid);

        DataByUid[data.uid]=data;
        _DatasHashSet.Add(data);
    
                    DataByName[data.name]=data;
    
                    if(!DatasByLabid.ContainsKey(data.labId))
                        DatasByLabid[data.labId]=new List<Data>();
                    DatasByLabid[data.labId].Add(data);
    
CmdDataForm.AddData(data);
            childAddAction?.Invoke(data);
            addAction?.Invoke(data);
            return data.uid;
        }
        public static void RemoveData(int uid)
        {            
            Init();
            if(!DataByUid.ContainsKey(uid))
                return;
               
            var data=DataByUid[uid];

                    _DatasHashSet.Remove(DataByUid[data.uid]);
                    DataByUid.Remove(data.uid);
                    
    
                    DataByName.Remove(data.name);
    
                    if(DatasByLabid.ContainsKey(data.labId))
                    {
                        DatasByLabid[data.labId].Remove(data);
                        if(DatasByLabid[data.labId].Count==0)
                            DatasByLabid.Remove(data.labId);
                    }
                    
    
CmdDataForm.RemoveData(uid);
            uidChain.PushId(data.uid);
            childRemoveAction?.Invoke(data);
            removeAction?.Invoke(data);
        }
        public static void Clear()
        {
            Init();
            var keys = new List<int>(DataByUid.Keys);
            foreach(var key in keys)
            {
                    RemoveData(key);
            }

        }
        
        public static void ClearAuto()
        {
            Init();
            var keys = new List<int>(DataByUid.Keys);
            foreach(var key in keys)
            {
                if(key < uidChain.cnt)
                    {
                        RemoveData(key);
                    }
            }
        }

         private static void RemoveChildren(CmdDataForm.Data data)
        {
            Init();
            if(data is Data)
               RemoveData(data.uid);      
        }
         private static void AddChildren(CmdDataForm.Data superData)
        {
            Init();
            if(superData is Data data)
               AddData(data);      
        }
        




            public static void ChangeUid(CmdDataForm.Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeUidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeName(CmdDataForm.Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DataByName.Remove(oldV);
                    DataByName[newV]=data;
 
                changeNameAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangePrmnames(CmdDataForm.Data superData,List<string> oldV,List<string> newV)
            {
                if(superData is Data data)
                {

                changePrmnamesAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangePrmtypes(CmdDataForm.Data superData,List<string> oldV,List<string> newV)
            {
                if(superData is Data data)
                {

                changePrmtypesAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeRetnames(CmdDataForm.Data superData,List<string> oldV,List<string> newV)
            {
                if(superData is Data data)
                {

                changeRetnamesAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeRettypes(CmdDataForm.Data superData,List<string> oldV,List<string> newV)
            {
                if(superData is Data data)
                {

                changeRettypesAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeDesc(CmdDataForm.Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                changeDescAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeDefaultcode(CmdDataForm.Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                changeDefaultcodeAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLabid(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                    DatasByLabid[oldV].Remove(data);
                    if(DatasByLabid[oldV].Count==0)
                        DatasByLabid.Remove(oldV);
                    if(!DatasByLabid.ContainsKey(newV))
                        DatasByLabid[newV]=new List<Data>();
                    DatasByLabid[newV].Add(data);
 
                changeLabidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLowesteditorstyle(Data superData,EditorStyle oldV,EditorStyle newV)
            {
                if(superData is Data data)
                {

                changeLowesteditorstyleAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeAllowasvoid(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                changeAllowasvoidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
    }
}
        