/* !!!IMPORTANT!!!: This file is a data table file. All code is generated by the table export BAT tool. Do not modify the .cs file directly. Please modify the original Excel file first and then regenerate the code using the tool.*/
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Z_ByteSerialize;
using Z_DesignStyle;
using Z_UnitSystem.Form;
using Z_Text.Form;
using Z_DataSystem.Form;
using Z_Map.Form;
using Z_Map;
using Z_Ui.Form;
using Z_Code.Form;

namespace Form
{

    public static partial class MapTerrainForm
    {

        

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Register()
        {

                MapBaseForm.childInitAction+=InitInternal;


                MapBaseForm.childRemoveAction+=RemoveChildren;
                MapBaseForm.childAddAction+=AddChildren;
            

            MapBaseForm.changeIdAction+=ChangeId;

            MapBaseForm.changeNameAction+=ChangeName;

            MapBaseForm.changeIconAction+=ChangeIcon;

            MapBaseForm.changeLabidAction+=ChangeLabid;

            Z_Json.extra[typeof(Data)]=((obj)=>{
            if(obj is Data data)
                return GetJoByData(data);
            return null;
            },(jo)=>{
            return GetDataByJo(jo);
            });
        }
        
        private static bool inited;

        public static Z_Chain.Chain idChain =>MapBaseForm.idChain;

        public static Action<Data> addAction;
        public static Action<Data> removeAction;
        public static Action childInitAction;
        public static Action<Data> childRemoveAction;
        public static Action<Data> childAddAction;
        
        public static Action<Data> beforeGetAction;

        public static Action<Data,int,int> changeIdAction;
                
        public static Action<Data,string,string> changeNameAction;
                
        public static Action<Data,string,string> changeInnerprefabnameAction;
                
        public static Action<Data,int,int> changeIconAction;
                
        public static Action<Data,int,int> changeLabidAction;
                


        public partial class Data : MapBaseForm.Data
        {

                    private string  _innerPrefabName;
                    /// <summary>
                    ///预制名称
                    ///</summary>
                    public string  innerPrefabName{
                                get{return _innerPrefabName;}
 set{

                    if(_DataById!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeInnerprefabname(this,_innerPrefabName,value); 
                    }
        
                _innerPrefabName = value;
                }
                 
                     }
                    
                    private float  _step;
                    /// <summary>
                    ///阶数
                    ///</summary>
                    public float  step{
                                get{return _step;}
private set{
        
                _step = value;
                }
                 
                     }
                    
            public Data(MapBaseForm.Data data):base(data.id,data.name,data.icon,data.labId)
            {
            }
            
            public Data(int id,string name,string innerPrefabName,int icon,float step,int labId):base(id,name,icon,labId)
            {

             this.id = id;
             this.name = name;
             this.innerPrefabName = innerPrefabName;
             this.icon = icon;
             this.step = step;
             this.labId = labId;

            }
            public void Reset(Data data)
            {

             this.id = data.id;
             this.name = data.name;
             this.innerPrefabName = data.innerPrefabName;
             this.icon = data.icon;
             this.step = data.step;
             this.labId = data.labId;
            }

                public Data Copy(bool sameId = true)
                {
        return new Data(sameId? id:idChain.GetId(),name,innerPrefabName,icon,step,labId);
                }
            
            public override  void BeforeGet()
            {
                base.BeforeGet();
                MapTerrainForm.beforeGetAction?.Invoke(this);
            }
        }

                   private static Data _defaultData=new Data(0,"","",0,0f,0);
                   public static Data defaultData=>_defaultData.Copy();


            static HashSet<Data> _DatasHashSet;
            static Dictionary<int, Data> _DataById;
            public static Dictionary<int, Data> DataById
            {
                get
                {
                    Init();
                    return _DataById;
                }
            }
    
            static Dictionary<string, List<Data>> _DatasByName;
            public static Dictionary<string, List<Data>> DatasByName
            {
                get
                {
                    Init();
                    return _DatasByName;
                }
            }
    
            static Dictionary<int, List<Data>> _DatasByLabid;
            public static Dictionary<int, List<Data>> DatasByLabid
            {
                get
                {
                    Init();
                    return _DatasByLabid;
                }
            }
    

        static public void Init()
        {

            MapBaseForm.Init();

        }
        public static void InitInternal()
        {
            if(inited)
                return;
            inited=true;  

        

                _DataById = new Dictionary<int, Data>() {

                {1000001,new Data(1000001,"ground","mapground",0,0f,0)},

                {1000002,new Data(1000002,"slope","mapslope",0,1f,0)},

                {1000003,new Data(1000003,"floor","mapfloor",0,0f,0)},

                };
                _DatasHashSet=new HashSet<Data>();
                
                    _DatasByName = new Dictionary<string, List<Data>>() {
    
                            {"ground",new List<Data>()},
        
                            {"slope",new List<Data>()},
        
                            {"floor",new List<Data>()},
        
                };

                    _DatasByName["ground"].Add(_DataById[1000001]);

                    _DatasByName["slope"].Add(_DataById[1000002]);

                    _DatasByName["floor"].Add(_DataById[1000003]);

                    _DatasByLabid = new Dictionary<int, List<Data>>() {
    
                            {0,new List<Data>()},
        
                };

                    _DatasByLabid[0].Add(_DataById[1000001]);

                    _DatasByLabid[0].Add(_DataById[1000002]);

                    _DatasByLabid[0].Add(_DataById[1000003]);


            childInitAction?.Invoke();
            

            foreach(var data in DataById.Values)
            {
                MapBaseForm.AddData(data);
            }


        
             
        }


        public static List<Data> GetDatasByJa(JArray ja)
        {
            Init();
            List<Data> lst=new List<Data>();
            foreach(JObject jo in ja)
            {
                if(jo.Get<int>("id")==0)
                    continue;
                lst.Add(GetDataByJo(jo));
            }
            return lst;
        }

        public static JArray GetJaByDatas()
        {
            Init();
            JArray ja=new JArray();
            foreach(Data data in _DataById.Values)
            {
                if(data.id==0)
                    continue;
                ja.Add(GetJoByData(data));
            }
            return ja;
        }

        public static Data GetDataByJo(JObject jo)
        {
            Init();

            Data data=new Data(

                jo.SelectToken("id")==null?defaultData.id:jo.Get<int>("id"),

                jo.SelectToken("name")==null?defaultData.name:jo.Get<string>("name"),

                jo.SelectToken("innerPrefabName")==null?defaultData.innerPrefabName:jo.Get<string>("innerPrefabName"),

                jo.SelectToken("icon")==null?defaultData.icon:jo.Get<int>("icon"),

                    _defaultData.step,

                jo.SelectToken("labId")==null?defaultData.labId:jo.Get<int>("labId")
                    );

            return data;
        }

        public static JObject GetJoByData(Data data)
        {
            Init();
            data.BeforeGet();

            JObject jo=new JObject();

            jo.Set<int>("id",data.id);

            jo.Set<string>("name",data.name);

            jo.Set<string>("innerPrefabName",data.innerPrefabName);

            jo.Set<int>("icon",data.icon);

            jo.Set<int>("labId",data.labId);

            return jo;
        }


        public static int AddData(Data data)
        {
            Init();
            if(DataById.ContainsKey(data.id))
                return data.id;
            if(data.id==-1)
            { 
                int id=idChain.GetId();
                if(id==-1)
                    return -1;
                data.id=id;  
            }
            idChain.PopId(data.id);

        DataById[data.id]=data;
        _DatasHashSet.Add(data);
    
                    if(!DatasByName.ContainsKey(data.name))
                        DatasByName[data.name]=new List<Data>();
                    DatasByName[data.name].Add(data);
    
                    if(!DatasByLabid.ContainsKey(data.labId))
                        DatasByLabid[data.labId]=new List<Data>();
                    DatasByLabid[data.labId].Add(data);
    
MapBaseForm.AddData(data);
            childAddAction?.Invoke(data);
            addAction?.Invoke(data);
            return data.id;
        }
        public static void RemoveData(int id)
        {            
            Init();
            if(!DataById.ContainsKey(id))
                return;
               
            var data=DataById[id];

                    _DatasHashSet.Remove(DataById[data.id]);
                    DataById.Remove(data.id);
                    
    
                    if(DatasByName.ContainsKey(data.name))
                    {
                        DatasByName[data.name].Remove(data);
                        if(DatasByName[data.name].Count==0)
                            DatasByName.Remove(data.name);
                    }
                    
    
                    if(DatasByLabid.ContainsKey(data.labId))
                    {
                        DatasByLabid[data.labId].Remove(data);
                        if(DatasByLabid[data.labId].Count==0)
                            DatasByLabid.Remove(data.labId);
                    }
                    
    
MapBaseForm.RemoveData(id);
            idChain.PushId(data.id);
            childRemoveAction?.Invoke(data);
            removeAction?.Invoke(data);
        }
        public static void Clear()
        {
            Init();
            var keys = new List<int>(DataById.Keys);
            foreach(var key in keys)
            {
                    RemoveData(key);
            }

        }
        
        public static void ClearAuto()
        {
            Init();
            var keys = new List<int>(DataById.Keys);
            foreach(var key in keys)
            {
                if(key < idChain.cnt)
                    {
                        RemoveData(key);
                    }
            }
        }

         private static void RemoveChildren(MapBaseForm.Data data)
        {
            Init();
            if(data is Data)
               RemoveData(data.id);      
        }
         private static void AddChildren(MapBaseForm.Data superData)
        {
            Init();
            if(superData is Data data)
               AddData(data);      
        }
        




            public static void ChangeId(MapBaseForm.Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeIdAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeName(MapBaseForm.Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DatasByName[oldV].Remove(data);
                    if(DatasByName[oldV].Count==0)
                        DatasByName.Remove(oldV);
                    if(!DatasByName.ContainsKey(newV))
                        DatasByName[newV]=new List<Data>();
                    DatasByName[newV].Add(data);
 
                changeNameAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeInnerprefabname(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                changeInnerprefabnameAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeIcon(MapBaseForm.Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeIconAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLabid(MapBaseForm.Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                    DatasByLabid[oldV].Remove(data);
                    if(DatasByLabid[oldV].Count==0)
                        DatasByLabid.Remove(oldV);
                    if(!DatasByLabid.ContainsKey(newV))
                        DatasByLabid[newV]=new List<Data>();
                    DatasByLabid[newV].Add(data);
 
                changeLabidAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
    }
}
        