/* !!!IMPORTANT!!!: This file is a data table file. All code is generated by the table export BAT tool. Do not modify the .cs file directly. Please modify the original Excel file first and then regenerate the code using the tool.*/
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Z_ByteSerialize;
using Z_DesignStyle;

namespace Z_DataSystem.Form
{

    public static partial class LabForm
    {
public static readonly int autoIdCnt=10000;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Register()
        {



            Z_Json.extra[typeof(Data)]=((obj)=>{
            if(obj is Data data)
                return GetJoByData(data);
            return null;
            },(jo)=>{
            return GetDataByJo(jo);
            });
        }
        
        private static bool inited;

        public static Z_Chain.Chain idChain ;

        public static Action<Data> addAction;
        public static Action<Data> removeAction;
        public static Action childInitAction;
        public static Action<Data> childRemoveAction;
        public static Action<Data> childAddAction;
        
        public static Action<Data> beforeGetAction;

        public static Action<Data,int,int> changeIdAction;
                
        public static Action<Data,string,string> changeLv1labAction;
                
        public static Action<Data,string,string> changeLv2labAction;
                
        public static Action<Data,string,string> changeLv3labAction;
                
        public static Action<Data,string,string> changeBelongAction;
                


        public partial class Data
        {

                    private int  _id;
                    /// <summary>
                    ///
                    ///</summary>
                    public int  id{
                                get{return _id;}
 set{

                    if(_DataById!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeId(this,_id,value); 
                    }
        
                _id = value;
                }
                 
                     }
                    
                    private string  _lv1Lab;
                    /// <summary>
                    ///
                    ///</summary>
                    public string  lv1Lab{
                                get{return _lv1Lab;}
 set{

                    if(_DataById!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLv1lab(this,_lv1Lab,value); 
                    }
        
                _lv1Lab = value;
                }
                 
                     }
                    
                    private string  _lv2Lab;
                    /// <summary>
                    ///
                    ///</summary>
                    public string  lv2Lab{
                                get{return _lv2Lab;}
 set{

                    if(_DataById!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLv2lab(this,_lv2Lab,value); 
                    }
        
                _lv2Lab = value;
                }
                 
                     }
                    
                    private string  _lv3Lab;
                    /// <summary>
                    ///
                    ///</summary>
                    public string  lv3Lab{
                                get{return _lv3Lab;}
 set{

                    if(_DataById!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeLv3lab(this,_lv3Lab,value); 
                    }
        
                _lv3Lab = value;
                }
                 
                     }
                    
                    private string  _belong;
                    /// <summary>
                    ///
                    ///</summary>
                    public string  belong{
                                get{return _belong;}
 set{

                    if(_DataById!=null&&_DatasHashSet.Contains(this))
                    {
                       ChangeBelong(this,_belong,value); 
                    }
        
                _belong = value;
                }
                 
                     }
                    
            public Data(int id,string lv1Lab,string lv2Lab,string lv3Lab,string belong)
            {

             this.id = id;
             this.lv1Lab = lv1Lab;
             this.lv2Lab = lv2Lab;
             this.lv3Lab = lv3Lab;
             this.belong = belong;

            }
            public void Reset(Data data)
            {

             this.id = data.id;
             this.lv1Lab = data.lv1Lab;
             this.lv2Lab = data.lv2Lab;
             this.lv3Lab = data.lv3Lab;
             this.belong = data.belong;
            }

                public Data Copy(bool sameId = true)
                {
        return new Data(sameId? id:idChain.GetId(),lv1Lab,lv2Lab,lv3Lab,belong);
                }
            
            public virtual  void BeforeGet()
            {
                
                LabForm.beforeGetAction?.Invoke(this);
            }
        }

                   private static Data _defaultData=new Data(0,"","","","");
                   public static Data defaultData=>_defaultData.Copy();


            static HashSet<Data> _DatasHashSet;
            static Dictionary<int, Data> _DataById;
            public static Dictionary<int, Data> DataById
            {
                get
                {
                    Init();
                    return _DataById;
                }
            }
    
            static Dictionary<(string,string), List<Data>> _DatasByLv1labBelong;
            public static Dictionary<(string,string), List<Data>> DatasByLv1labBelong
            {
                get
                {
                    Init();
                    return _DatasByLv1labBelong;
                }
            }
    
            static Dictionary<(string,string,string), List<Data>> _DatasByLv1labLv2labBelong;
            public static Dictionary<(string,string,string), List<Data>> DatasByLv1labLv2labBelong
            {
                get
                {
                    Init();
                    return _DatasByLv1labLv2labBelong;
                }
            }
    
            static Dictionary<(string,string,string,string), List<Data>> _DatasByLv1labLv2labLv3labBelong;
            public static Dictionary<(string,string,string,string), List<Data>> DatasByLv1labLv2labLv3labBelong
            {
                get
                {
                    Init();
                    return _DatasByLv1labLv2labLv3labBelong;
                }
            }
    
            static Dictionary<string, List<Data>> _DatasByBelong;
            public static Dictionary<string, List<Data>> DatasByBelong
            {
                get
                {
                    Init();
                    return _DatasByBelong;
                }
            }
    
            static Dictionary<(string,string,string,string), Data> _DataByLv1labLv2labLv3labBelong;
            public static Dictionary<(string,string,string,string), Data> DataByLv1labLv2labLv3labBelong
            {
                get
                {
                    Init();
                    return _DataByLv1labLv2labLv3labBelong;
                }
            }
    

        static public void Init()
        {

            InitInternal();
        }
        public static void InitInternal()
        {
            if(inited)
                return;
            inited=true;  
idChain=new Z_Chain.Chain (autoIdCnt);

                _DataById = new Dictionary<int, Data>() {

                {10001,new Data(10001,"basic","audio","","GameCmdDataForm")},

                {10002,new Data(10002,"basic","const","","GameCmdDataForm")},

                {10003,new Data(10003,"basic","list","","GameCmdDataForm")},

                {10004,new Data(10004,"basic","math","","GameCmdDataForm")},

                {10005,new Data(10005,"basic","process","","GameCmdDataForm")},

                {10006,new Data(10006,"basic","variable","","GameCmdDataForm")},

                {10007,new Data(10007,"character","anim","","GameCmdDataForm")},

                {10008,new Data(10008,"character","detect","","GameCmdDataForm")},

                {10009,new Data(10009,"character","parameter","","GameCmdDataForm")},

                {10010,new Data(10010,"character","skill","","GameCmdDataForm")},

                {10011,new Data(10011,"character","system","","GameCmdDataForm")},

                {10012,new Data(10012,"character","transform","","GameCmdDataForm")},

                {10013,new Data(10013,"effect","system","","GameCmdDataForm")},

                {10014,new Data(10014,"item","backpack","","GameCmdDataForm")},

                {10015,new Data(10015,"mission","system","","GameCmdDataForm")},

                {10016,new Data(10016,"sceneObject","detect","","GameCmdDataForm")},

                {10017,new Data(10017,"sceneObject","parameter","","GameCmdDataForm")},

                {10018,new Data(10018,"sceneObject","system","","GameCmdDataForm")},

                {10019,new Data(10019,"sceneObject","transform","","GameCmdDataForm")},

                {10020,new Data(10020,"skill","parameter","","GameCmdDataForm")},

                {10021,new Data(10021,"skill","system","","GameCmdDataForm")},

                {10022,new Data(10022,"ui","dialog","","GameCmdDataForm")},

                {10023,new Data(10023,"ui","image","","GameCmdDataForm")},

                {10024,new Data(10024,"ui","notice","","GameCmdDataForm")},

                {10025,new Data(10025,"ui","window","","GameCmdDataForm")},

                };
                _DatasHashSet=new HashSet<Data>();
                
                    _DataByLv1labLv2labLv3labBelong = new Dictionary<(string,string,string,string), Data>() {
    
                        {("basic","audio","","GameCmdDataForm"),_DataById[10001]},
    
                        {("basic","const","","GameCmdDataForm"),_DataById[10002]},
    
                        {("basic","list","","GameCmdDataForm"),_DataById[10003]},
    
                        {("basic","math","","GameCmdDataForm"),_DataById[10004]},
    
                        {("basic","process","","GameCmdDataForm"),_DataById[10005]},
    
                        {("basic","variable","","GameCmdDataForm"),_DataById[10006]},
    
                        {("character","anim","","GameCmdDataForm"),_DataById[10007]},
    
                        {("character","detect","","GameCmdDataForm"),_DataById[10008]},
    
                        {("character","parameter","","GameCmdDataForm"),_DataById[10009]},
    
                        {("character","skill","","GameCmdDataForm"),_DataById[10010]},
    
                        {("character","system","","GameCmdDataForm"),_DataById[10011]},
    
                        {("character","transform","","GameCmdDataForm"),_DataById[10012]},
    
                        {("effect","system","","GameCmdDataForm"),_DataById[10013]},
    
                        {("item","backpack","","GameCmdDataForm"),_DataById[10014]},
    
                        {("mission","system","","GameCmdDataForm"),_DataById[10015]},
    
                        {("sceneObject","detect","","GameCmdDataForm"),_DataById[10016]},
    
                        {("sceneObject","parameter","","GameCmdDataForm"),_DataById[10017]},
    
                        {("sceneObject","system","","GameCmdDataForm"),_DataById[10018]},
    
                        {("sceneObject","transform","","GameCmdDataForm"),_DataById[10019]},
    
                        {("skill","parameter","","GameCmdDataForm"),_DataById[10020]},
    
                        {("skill","system","","GameCmdDataForm"),_DataById[10021]},
    
                        {("ui","dialog","","GameCmdDataForm"),_DataById[10022]},
    
                        {("ui","image","","GameCmdDataForm"),_DataById[10023]},
    
                        {("ui","notice","","GameCmdDataForm"),_DataById[10024]},
    
                        {("ui","window","","GameCmdDataForm"),_DataById[10025]},
    
                    
                    };
                    foreach(var v in _DataById.Values)
                    {
                        _DatasHashSet.Add(v);
                    }
    
                    _DatasByLv1labBelong = new Dictionary<(string,string), List<Data>>() {
    
                            {("basic","GameCmdDataForm"),new List<Data>()},
        
                            {("character","GameCmdDataForm"),new List<Data>()},
        
                            {("effect","GameCmdDataForm"),new List<Data>()},
        
                            {("item","GameCmdDataForm"),new List<Data>()},
        
                            {("mission","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","GameCmdDataForm"),new List<Data>()},
        
                            {("skill","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","GameCmdDataForm"),new List<Data>()},
        
                };

                    _DatasByLv1labBelong[("basic","GameCmdDataForm")].Add(_DataById[10001]);

                    _DatasByLv1labBelong[("basic","GameCmdDataForm")].Add(_DataById[10002]);

                    _DatasByLv1labBelong[("basic","GameCmdDataForm")].Add(_DataById[10003]);

                    _DatasByLv1labBelong[("basic","GameCmdDataForm")].Add(_DataById[10004]);

                    _DatasByLv1labBelong[("basic","GameCmdDataForm")].Add(_DataById[10005]);

                    _DatasByLv1labBelong[("basic","GameCmdDataForm")].Add(_DataById[10006]);

                    _DatasByLv1labBelong[("character","GameCmdDataForm")].Add(_DataById[10007]);

                    _DatasByLv1labBelong[("character","GameCmdDataForm")].Add(_DataById[10008]);

                    _DatasByLv1labBelong[("character","GameCmdDataForm")].Add(_DataById[10009]);

                    _DatasByLv1labBelong[("character","GameCmdDataForm")].Add(_DataById[10010]);

                    _DatasByLv1labBelong[("character","GameCmdDataForm")].Add(_DataById[10011]);

                    _DatasByLv1labBelong[("character","GameCmdDataForm")].Add(_DataById[10012]);

                    _DatasByLv1labBelong[("effect","GameCmdDataForm")].Add(_DataById[10013]);

                    _DatasByLv1labBelong[("item","GameCmdDataForm")].Add(_DataById[10014]);

                    _DatasByLv1labBelong[("mission","GameCmdDataForm")].Add(_DataById[10015]);

                    _DatasByLv1labBelong[("sceneObject","GameCmdDataForm")].Add(_DataById[10016]);

                    _DatasByLv1labBelong[("sceneObject","GameCmdDataForm")].Add(_DataById[10017]);

                    _DatasByLv1labBelong[("sceneObject","GameCmdDataForm")].Add(_DataById[10018]);

                    _DatasByLv1labBelong[("sceneObject","GameCmdDataForm")].Add(_DataById[10019]);

                    _DatasByLv1labBelong[("skill","GameCmdDataForm")].Add(_DataById[10020]);

                    _DatasByLv1labBelong[("skill","GameCmdDataForm")].Add(_DataById[10021]);

                    _DatasByLv1labBelong[("ui","GameCmdDataForm")].Add(_DataById[10022]);

                    _DatasByLv1labBelong[("ui","GameCmdDataForm")].Add(_DataById[10023]);

                    _DatasByLv1labBelong[("ui","GameCmdDataForm")].Add(_DataById[10024]);

                    _DatasByLv1labBelong[("ui","GameCmdDataForm")].Add(_DataById[10025]);

                    _DatasByLv1labLv2labBelong = new Dictionary<(string,string,string), List<Data>>() {
    
                            {("basic","audio","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","const","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","list","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","math","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","process","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","variable","GameCmdDataForm"),new List<Data>()},
        
                            {("character","anim","GameCmdDataForm"),new List<Data>()},
        
                            {("character","detect","GameCmdDataForm"),new List<Data>()},
        
                            {("character","parameter","GameCmdDataForm"),new List<Data>()},
        
                            {("character","skill","GameCmdDataForm"),new List<Data>()},
        
                            {("character","system","GameCmdDataForm"),new List<Data>()},
        
                            {("character","transform","GameCmdDataForm"),new List<Data>()},
        
                            {("effect","system","GameCmdDataForm"),new List<Data>()},
        
                            {("item","backpack","GameCmdDataForm"),new List<Data>()},
        
                            {("mission","system","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","detect","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","parameter","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","system","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","transform","GameCmdDataForm"),new List<Data>()},
        
                            {("skill","parameter","GameCmdDataForm"),new List<Data>()},
        
                            {("skill","system","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","dialog","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","image","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","notice","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","window","GameCmdDataForm"),new List<Data>()},
        
                };

                    _DatasByLv1labLv2labBelong[("basic","audio","GameCmdDataForm")].Add(_DataById[10001]);

                    _DatasByLv1labLv2labBelong[("basic","const","GameCmdDataForm")].Add(_DataById[10002]);

                    _DatasByLv1labLv2labBelong[("basic","list","GameCmdDataForm")].Add(_DataById[10003]);

                    _DatasByLv1labLv2labBelong[("basic","math","GameCmdDataForm")].Add(_DataById[10004]);

                    _DatasByLv1labLv2labBelong[("basic","process","GameCmdDataForm")].Add(_DataById[10005]);

                    _DatasByLv1labLv2labBelong[("basic","variable","GameCmdDataForm")].Add(_DataById[10006]);

                    _DatasByLv1labLv2labBelong[("character","anim","GameCmdDataForm")].Add(_DataById[10007]);

                    _DatasByLv1labLv2labBelong[("character","detect","GameCmdDataForm")].Add(_DataById[10008]);

                    _DatasByLv1labLv2labBelong[("character","parameter","GameCmdDataForm")].Add(_DataById[10009]);

                    _DatasByLv1labLv2labBelong[("character","skill","GameCmdDataForm")].Add(_DataById[10010]);

                    _DatasByLv1labLv2labBelong[("character","system","GameCmdDataForm")].Add(_DataById[10011]);

                    _DatasByLv1labLv2labBelong[("character","transform","GameCmdDataForm")].Add(_DataById[10012]);

                    _DatasByLv1labLv2labBelong[("effect","system","GameCmdDataForm")].Add(_DataById[10013]);

                    _DatasByLv1labLv2labBelong[("item","backpack","GameCmdDataForm")].Add(_DataById[10014]);

                    _DatasByLv1labLv2labBelong[("mission","system","GameCmdDataForm")].Add(_DataById[10015]);

                    _DatasByLv1labLv2labBelong[("sceneObject","detect","GameCmdDataForm")].Add(_DataById[10016]);

                    _DatasByLv1labLv2labBelong[("sceneObject","parameter","GameCmdDataForm")].Add(_DataById[10017]);

                    _DatasByLv1labLv2labBelong[("sceneObject","system","GameCmdDataForm")].Add(_DataById[10018]);

                    _DatasByLv1labLv2labBelong[("sceneObject","transform","GameCmdDataForm")].Add(_DataById[10019]);

                    _DatasByLv1labLv2labBelong[("skill","parameter","GameCmdDataForm")].Add(_DataById[10020]);

                    _DatasByLv1labLv2labBelong[("skill","system","GameCmdDataForm")].Add(_DataById[10021]);

                    _DatasByLv1labLv2labBelong[("ui","dialog","GameCmdDataForm")].Add(_DataById[10022]);

                    _DatasByLv1labLv2labBelong[("ui","image","GameCmdDataForm")].Add(_DataById[10023]);

                    _DatasByLv1labLv2labBelong[("ui","notice","GameCmdDataForm")].Add(_DataById[10024]);

                    _DatasByLv1labLv2labBelong[("ui","window","GameCmdDataForm")].Add(_DataById[10025]);

                    _DatasByLv1labLv2labLv3labBelong = new Dictionary<(string,string,string,string), List<Data>>() {
    
                            {("basic","audio","","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","const","","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","list","","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","math","","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","process","","GameCmdDataForm"),new List<Data>()},
        
                            {("basic","variable","","GameCmdDataForm"),new List<Data>()},
        
                            {("character","anim","","GameCmdDataForm"),new List<Data>()},
        
                            {("character","detect","","GameCmdDataForm"),new List<Data>()},
        
                            {("character","parameter","","GameCmdDataForm"),new List<Data>()},
        
                            {("character","skill","","GameCmdDataForm"),new List<Data>()},
        
                            {("character","system","","GameCmdDataForm"),new List<Data>()},
        
                            {("character","transform","","GameCmdDataForm"),new List<Data>()},
        
                            {("effect","system","","GameCmdDataForm"),new List<Data>()},
        
                            {("item","backpack","","GameCmdDataForm"),new List<Data>()},
        
                            {("mission","system","","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","detect","","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","parameter","","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","system","","GameCmdDataForm"),new List<Data>()},
        
                            {("sceneObject","transform","","GameCmdDataForm"),new List<Data>()},
        
                            {("skill","parameter","","GameCmdDataForm"),new List<Data>()},
        
                            {("skill","system","","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","dialog","","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","image","","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","notice","","GameCmdDataForm"),new List<Data>()},
        
                            {("ui","window","","GameCmdDataForm"),new List<Data>()},
        
                };

                    _DatasByLv1labLv2labLv3labBelong[("basic","audio","","GameCmdDataForm")].Add(_DataById[10001]);

                    _DatasByLv1labLv2labLv3labBelong[("basic","const","","GameCmdDataForm")].Add(_DataById[10002]);

                    _DatasByLv1labLv2labLv3labBelong[("basic","list","","GameCmdDataForm")].Add(_DataById[10003]);

                    _DatasByLv1labLv2labLv3labBelong[("basic","math","","GameCmdDataForm")].Add(_DataById[10004]);

                    _DatasByLv1labLv2labLv3labBelong[("basic","process","","GameCmdDataForm")].Add(_DataById[10005]);

                    _DatasByLv1labLv2labLv3labBelong[("basic","variable","","GameCmdDataForm")].Add(_DataById[10006]);

                    _DatasByLv1labLv2labLv3labBelong[("character","anim","","GameCmdDataForm")].Add(_DataById[10007]);

                    _DatasByLv1labLv2labLv3labBelong[("character","detect","","GameCmdDataForm")].Add(_DataById[10008]);

                    _DatasByLv1labLv2labLv3labBelong[("character","parameter","","GameCmdDataForm")].Add(_DataById[10009]);

                    _DatasByLv1labLv2labLv3labBelong[("character","skill","","GameCmdDataForm")].Add(_DataById[10010]);

                    _DatasByLv1labLv2labLv3labBelong[("character","system","","GameCmdDataForm")].Add(_DataById[10011]);

                    _DatasByLv1labLv2labLv3labBelong[("character","transform","","GameCmdDataForm")].Add(_DataById[10012]);

                    _DatasByLv1labLv2labLv3labBelong[("effect","system","","GameCmdDataForm")].Add(_DataById[10013]);

                    _DatasByLv1labLv2labLv3labBelong[("item","backpack","","GameCmdDataForm")].Add(_DataById[10014]);

                    _DatasByLv1labLv2labLv3labBelong[("mission","system","","GameCmdDataForm")].Add(_DataById[10015]);

                    _DatasByLv1labLv2labLv3labBelong[("sceneObject","detect","","GameCmdDataForm")].Add(_DataById[10016]);

                    _DatasByLv1labLv2labLv3labBelong[("sceneObject","parameter","","GameCmdDataForm")].Add(_DataById[10017]);

                    _DatasByLv1labLv2labLv3labBelong[("sceneObject","system","","GameCmdDataForm")].Add(_DataById[10018]);

                    _DatasByLv1labLv2labLv3labBelong[("sceneObject","transform","","GameCmdDataForm")].Add(_DataById[10019]);

                    _DatasByLv1labLv2labLv3labBelong[("skill","parameter","","GameCmdDataForm")].Add(_DataById[10020]);

                    _DatasByLv1labLv2labLv3labBelong[("skill","system","","GameCmdDataForm")].Add(_DataById[10021]);

                    _DatasByLv1labLv2labLv3labBelong[("ui","dialog","","GameCmdDataForm")].Add(_DataById[10022]);

                    _DatasByLv1labLv2labLv3labBelong[("ui","image","","GameCmdDataForm")].Add(_DataById[10023]);

                    _DatasByLv1labLv2labLv3labBelong[("ui","notice","","GameCmdDataForm")].Add(_DataById[10024]);

                    _DatasByLv1labLv2labLv3labBelong[("ui","window","","GameCmdDataForm")].Add(_DataById[10025]);

                    _DatasByBelong = new Dictionary<string, List<Data>>() {
    
                            {"GameCmdDataForm",new List<Data>()},
        
                };

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10001]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10002]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10003]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10004]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10005]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10006]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10007]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10008]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10009]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10010]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10011]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10012]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10013]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10014]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10015]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10016]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10017]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10018]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10019]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10020]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10021]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10022]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10023]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10024]);

                    _DatasByBelong["GameCmdDataForm"].Add(_DataById[10025]);


            childInitAction?.Invoke();
            

foreach(var k in _DataById.Keys){ idChain.PopId(k); }
             
        }


        public static List<Data> GetDatasByJa(JArray ja)
        {
            Init();
            List<Data> lst=new List<Data>();
            foreach(JObject jo in ja)
            {
                if(jo.Get<int>("id")==0)
                    continue;
                lst.Add(GetDataByJo(jo));
            }
            return lst;
        }

        public static JArray GetJaByDatas()
        {
            Init();
            JArray ja=new JArray();
            foreach(Data data in _DataById.Values)
            {
                if(data.id==0)
                    continue;
                ja.Add(GetJoByData(data));
            }
            return ja;
        }

        public static Data GetDataByJo(JObject jo)
        {
            Init();

            Data data=new Data(

                jo.SelectToken("id")==null?defaultData.id:jo.Get<int>("id"),

                jo.SelectToken("lv1Lab")==null?defaultData.lv1Lab:jo.Get<string>("lv1Lab"),

                jo.SelectToken("lv2Lab")==null?defaultData.lv2Lab:jo.Get<string>("lv2Lab"),

                jo.SelectToken("lv3Lab")==null?defaultData.lv3Lab:jo.Get<string>("lv3Lab"),

                jo.SelectToken("belong")==null?defaultData.belong:jo.Get<string>("belong")
                    );

            return data;
        }

        public static JObject GetJoByData(Data data)
        {
            Init();
            data.BeforeGet();

            JObject jo=new JObject();

            jo.Set<int>("id",data.id);

            jo.Set<string>("lv1Lab",data.lv1Lab);

            jo.Set<string>("lv2Lab",data.lv2Lab);

            jo.Set<string>("lv3Lab",data.lv3Lab);

            jo.Set<string>("belong",data.belong);

            return jo;
        }


        public static int AddData(Data data)
        {
            Init();
            if(DataById.ContainsKey(data.id))
                return data.id;
            if(data.id==-1)
            { 
                int id=idChain.GetId();
                if(id==-1)
                    return -1;
                data.id=id;  
            }
            idChain.PopId(data.id);

        DataById[data.id]=data;
        _DatasHashSet.Add(data);
    
                    DataByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)]=data;
    
                    if(!DatasByLv1labBelong.ContainsKey((data.lv1Lab,data.belong)))
                        DatasByLv1labBelong[(data.lv1Lab,data.belong)]=new List<Data>();
                    DatasByLv1labBelong[(data.lv1Lab,data.belong)].Add(data);
    
                    if(!DatasByLv1labLv2labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,data.belong)))
                        DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,data.belong)].Add(data);
    
                    if(!DatasByLv1labLv2labLv3labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)))
                        DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)].Add(data);
    
                    if(!DatasByBelong.ContainsKey(data.belong))
                        DatasByBelong[data.belong]=new List<Data>();
                    DatasByBelong[data.belong].Add(data);
    

            childAddAction?.Invoke(data);
            addAction?.Invoke(data);
            return data.id;
        }
        public static void RemoveData(int id)
        {            
            Init();
            if(!DataById.ContainsKey(id))
                return;
               
            var data=DataById[id];

                    _DatasHashSet.Remove(DataById[data.id]);
                    DataById.Remove(data.id);
                    
    
                    DataByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong));
    
                    if(DatasByLv1labBelong.ContainsKey((data.lv1Lab,data.belong)))
                    {
                        DatasByLv1labBelong[(data.lv1Lab,data.belong)].Remove(data);
                        if(DatasByLv1labBelong[(data.lv1Lab,data.belong)].Count==0)
                            DatasByLv1labBelong.Remove((data.lv1Lab,data.belong));
                    }
                    
    
                    if(DatasByLv1labLv2labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,data.belong)))
                    {
                        DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,data.belong)].Remove(data);
                        if(DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,data.belong)].Count==0)
                            DatasByLv1labLv2labBelong.Remove((data.lv1Lab,data.lv2Lab,data.belong));
                    }
                    
    
                    if(DatasByLv1labLv2labLv3labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)))
                    {
                        DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)].Remove(data);
                        if(DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong)].Count==0)
                            DatasByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,data.lv2Lab,data.lv3Lab,data.belong));
                    }
                    
    
                    if(DatasByBelong.ContainsKey(data.belong))
                    {
                        DatasByBelong[data.belong].Remove(data);
                        if(DatasByBelong[data.belong].Count==0)
                            DatasByBelong.Remove(data.belong);
                    }
                    
    

            idChain.PushId(data.id);
            childRemoveAction?.Invoke(data);
            removeAction?.Invoke(data);
        }
        public static void Clear()
        {
            Init();
            var keys = new List<int>(DataById.Keys);
            foreach(var key in keys)
            {
                    RemoveData(key);
            }

        }
        
        public static void ClearAuto()
        {
            Init();
            var keys = new List<int>(DataById.Keys);
            foreach(var key in keys)
            {
                if(key < idChain.cnt)
                    {
                        RemoveData(key);
                    }
            }
        }

         private static void RemoveChildren(Data data)
        {
            Init();
            if(data is Data)
               RemoveData(data.id);      
        }
         private static void AddChildren(Data superData)
        {
            Init();
            if(superData is Data data)
               AddData(data);      
        }
        




            public static void ChangeId(Data superData,int oldV,int newV)
            {
                if(superData is Data data)
                {

                changeIdAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLv1lab(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DatasByLv1labBelong[(oldV,data.belong)].Remove(data);
                    if(DatasByLv1labBelong[(oldV,data.belong)].Count==0)
                        DatasByLv1labBelong.Remove((oldV,data.belong));
                    if(!DatasByLv1labBelong.ContainsKey((newV,data.belong)))
                        DatasByLv1labBelong[(newV,data.belong)]=new List<Data>();
                    DatasByLv1labBelong[(newV,data.belong)].Add(data);
 
                    DatasByLv1labLv2labBelong[(oldV,data.lv2Lab,data.belong)].Remove(data);
                    if(DatasByLv1labLv2labBelong[(oldV,data.lv2Lab,data.belong)].Count==0)
                        DatasByLv1labLv2labBelong.Remove((oldV,data.lv2Lab,data.belong));
                    if(!DatasByLv1labLv2labBelong.ContainsKey((newV,data.lv2Lab,data.belong)))
                        DatasByLv1labLv2labBelong[(newV,data.lv2Lab,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labBelong[(newV,data.lv2Lab,data.belong)].Add(data);
 
                    DataByLv1labLv2labLv3labBelong.Remove((oldV,data.lv2Lab,data.lv3Lab,data.belong));
                    DataByLv1labLv2labLv3labBelong[(newV,data.lv2Lab,data.lv3Lab,data.belong)]=data;
 
                    DatasByLv1labLv2labLv3labBelong[(oldV,data.lv2Lab,data.lv3Lab,data.belong)].Remove(data);
                    if(DatasByLv1labLv2labLv3labBelong[(oldV,data.lv2Lab,data.lv3Lab,data.belong)].Count==0)
                        DatasByLv1labLv2labLv3labBelong.Remove((oldV,data.lv2Lab,data.lv3Lab,data.belong));
                    if(!DatasByLv1labLv2labLv3labBelong.ContainsKey((newV,data.lv2Lab,data.lv3Lab,data.belong)))
                        DatasByLv1labLv2labLv3labBelong[(newV,data.lv2Lab,data.lv3Lab,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labLv3labBelong[(newV,data.lv2Lab,data.lv3Lab,data.belong)].Add(data);
 
                changeLv1labAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLv2lab(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DatasByLv1labLv2labBelong[(data.lv1Lab,oldV,data.belong)].Remove(data);
                    if(DatasByLv1labLv2labBelong[(data.lv1Lab,oldV,data.belong)].Count==0)
                        DatasByLv1labLv2labBelong.Remove((data.lv1Lab,oldV,data.belong));
                    if(!DatasByLv1labLv2labBelong.ContainsKey((data.lv1Lab,newV,data.belong)))
                        DatasByLv1labLv2labBelong[(data.lv1Lab,newV,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labBelong[(data.lv1Lab,newV,data.belong)].Add(data);
 
                    DataByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,oldV,data.lv3Lab,data.belong));
                    DataByLv1labLv2labLv3labBelong[(data.lv1Lab,newV,data.lv3Lab,data.belong)]=data;
 
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,oldV,data.lv3Lab,data.belong)].Remove(data);
                    if(DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,oldV,data.lv3Lab,data.belong)].Count==0)
                        DatasByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,oldV,data.lv3Lab,data.belong));
                    if(!DatasByLv1labLv2labLv3labBelong.ContainsKey((data.lv1Lab,newV,data.lv3Lab,data.belong)))
                        DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,newV,data.lv3Lab,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,newV,data.lv3Lab,data.belong)].Add(data);
 
                changeLv2labAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeLv3lab(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DataByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,data.lv2Lab,oldV,data.belong));
                    DataByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,newV,data.belong)]=data;
 
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,oldV,data.belong)].Remove(data);
                    if(DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,oldV,data.belong)].Count==0)
                        DatasByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,data.lv2Lab,oldV,data.belong));
                    if(!DatasByLv1labLv2labLv3labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,newV,data.belong)))
                        DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,newV,data.belong)]=new List<Data>();
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,newV,data.belong)].Add(data);
 
                changeLv3labAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
            public static void ChangeBelong(Data superData,string oldV,string newV)
            {
                if(superData is Data data)
                {

                    DatasByBelong[oldV].Remove(data);
                    if(DatasByBelong[oldV].Count==0)
                        DatasByBelong.Remove(oldV);
                    if(!DatasByBelong.ContainsKey(newV))
                        DatasByBelong[newV]=new List<Data>();
                    DatasByBelong[newV].Add(data);
 
                    DatasByLv1labBelong[(data.lv1Lab,oldV)].Remove(data);
                    if(DatasByLv1labBelong[(data.lv1Lab,oldV)].Count==0)
                        DatasByLv1labBelong.Remove((data.lv1Lab,oldV));
                    if(!DatasByLv1labBelong.ContainsKey((data.lv1Lab,newV)))
                        DatasByLv1labBelong[(data.lv1Lab,newV)]=new List<Data>();
                    DatasByLv1labBelong[(data.lv1Lab,newV)].Add(data);
 
                    DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,oldV)].Remove(data);
                    if(DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,oldV)].Count==0)
                        DatasByLv1labLv2labBelong.Remove((data.lv1Lab,data.lv2Lab,oldV));
                    if(!DatasByLv1labLv2labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,newV)))
                        DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,newV)]=new List<Data>();
                    DatasByLv1labLv2labBelong[(data.lv1Lab,data.lv2Lab,newV)].Add(data);
 
                    DataByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,data.lv2Lab,data.lv3Lab,oldV));
                    DataByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,newV)]=data;
 
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,oldV)].Remove(data);
                    if(DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,oldV)].Count==0)
                        DatasByLv1labLv2labLv3labBelong.Remove((data.lv1Lab,data.lv2Lab,data.lv3Lab,oldV));
                    if(!DatasByLv1labLv2labLv3labBelong.ContainsKey((data.lv1Lab,data.lv2Lab,data.lv3Lab,newV)))
                        DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,newV)]=new List<Data>();
                    DatasByLv1labLv2labLv3labBelong[(data.lv1Lab,data.lv2Lab,data.lv3Lab,newV)].Add(data);
 
                changeBelongAction?.Invoke(data,oldV,newV);
                }
                    
            }
            
    }
}
        